<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Foundations | Probability and Statistics: Making Principled Decisions in an Uncertain World</title>
  <meta name="description" content="OER textbook designed to support calculus-based introductory undergraduate statistics training. At Texas A&amp;M University, this book is appropriate for the two-course sequence STAT 211 &amp; 212." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Foundations | Probability and Statistics: Making Principled Decisions in an Uncertain World" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="OER textbook designed to support calculus-based introductory undergraduate statistics training. At Texas A&amp;M University, this book is appropriate for the two-course sequence STAT 211 &amp; 212." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Foundations | Probability and Statistics: Making Principled Decisions in an Uncertain World" />
  
  <meta name="twitter:description" content="OER textbook designed to support calculus-based introductory undergraduate statistics training. At Texas A&amp;M University, this book is appropriate for the two-course sequence STAT 211 &amp; 212." />
  

<meta name="author" content="Alan Dabney, Scott Crawford, Darren Homrighausen" />


<meta name="date" content="2026-07-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="chap-probability.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.25.2/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about"><i class="fa fa-check"></i><b>1.1</b> About</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.2</b> R</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#supplemental-resources"><i class="fa fa-check"></i><b>1.3</b> Supplemental Resources</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.4</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-foundations.html"><a href="chap-foundations.html"><i class="fa fa-check"></i><b>2</b> Foundations</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-foundations.html"><a href="chap-foundations.html#what-is-statistics"><i class="fa fa-check"></i><b>2.1</b> What is Statistics?</a></li>
<li class="chapter" data-level="2.2" data-path="chap-foundations.html"><a href="chap-foundations.html#populations-and-parameters-samples-and-statistics"><i class="fa fa-check"></i><b>2.2</b> Populations and Parameters, Samples and Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="chap-foundations.html"><a href="chap-foundations.html#obtaining-data"><i class="fa fa-check"></i><b>2.3</b> Obtaining Data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chap-foundations.html"><a href="chap-foundations.html#chap-foundations-sampling"><i class="fa fa-check"></i><b>2.3.1</b> Sampling</a></li>
<li class="chapter" data-level="2.3.2" data-path="chap-foundations.html"><a href="chap-foundations.html#chap-foundations-observational-experiment"><i class="fa fa-check"></i><b>2.3.2</b> Observational Studies and Experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-foundations.html"><a href="chap-foundations.html#sec-foundations-nature-of-data"><i class="fa fa-check"></i><b>2.4</b> The Nature of Data</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chap-foundations.html"><a href="chap-foundations.html#randomness-and-uncertainty"><i class="fa fa-check"></i><b>2.4.1</b> Randomness and Uncertainty</a></li>
<li class="chapter" data-level="2.4.2" data-path="chap-foundations.html"><a href="chap-foundations.html#random-variables"><i class="fa fa-check"></i><b>2.4.2</b> Random Variables</a></li>
<li class="chapter" data-level="2.4.3" data-path="chap-foundations.html"><a href="chap-foundations.html#notation"><i class="fa fa-check"></i><b>2.4.3</b> Notation</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chap-foundations.html"><a href="chap-foundations.html#numerical-summaries"><i class="fa fa-check"></i><b>2.5</b> Summary Statistics</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="chap-foundations.html"><a href="chap-foundations.html#mean"><i class="fa fa-check"></i><b>2.5.1</b> Mean</a></li>
<li class="chapter" data-level="2.5.2" data-path="chap-foundations.html"><a href="chap-foundations.html#sec-percentiles-median"><i class="fa fa-check"></i><b>2.5.2</b> Percentiles and Median</a></li>
<li class="chapter" data-level="2.5.3" data-path="chap-foundations.html"><a href="chap-foundations.html#variance-and-standard-deviation"><i class="fa fa-check"></i><b>2.5.3</b> Variance and Standard Deviation</a></li>
<li class="chapter" data-level="2.5.4" data-path="chap-foundations.html"><a href="chap-foundations.html#extreme-values-and-robust-statistics"><i class="fa fa-check"></i><b>2.5.4</b> Extreme Values and Robust Statistics</a></li>
<li class="chapter" data-level="2.5.5" data-path="chap-foundations.html"><a href="chap-foundations.html#frequency-and-relative-frequency"><i class="fa fa-check"></i><b>2.5.5</b> Frequency and Relative Frequency</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chap-foundations.html"><a href="chap-foundations.html#graphical-summaries"><i class="fa fa-check"></i><b>2.6</b> Graphical Summaries</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="chap-foundations.html"><a href="chap-foundations.html#boxplot"><i class="fa fa-check"></i><b>2.6.1</b> Boxplot</a></li>
<li class="chapter" data-level="2.6.2" data-path="chap-foundations.html"><a href="chap-foundations.html#histogram"><i class="fa fa-check"></i><b>2.6.2</b> Histogram</a></li>
<li class="chapter" data-level="2.6.3" data-path="chap-foundations.html"><a href="chap-foundations.html#the-shape-of-a-distribution"><i class="fa fa-check"></i><b>2.6.3</b> The Shape of a Distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-probability.html"><a href="chap-probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-probability.html"><a href="chap-probability.html#motivation-and-intuition"><i class="fa fa-check"></i><b>3.1</b> Motivation and Intuition</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="chap-probability.html"><a href="chap-probability.html#previewing-statistical-inference"><i class="fa fa-check"></i><b>3.1.1</b> Previewing Statistical Inference</a></li>
<li class="chapter" data-level="3.1.2" data-path="chap-probability.html"><a href="chap-probability.html#probability-a-long-run-average"><i class="fa fa-check"></i><b>3.1.2</b> Probability: A "Long-Run Average"</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chap-probability.html"><a href="chap-probability.html#sample-spaces-and-events"><i class="fa fa-check"></i><b>3.2</b> Sample Spaces and Events</a></li>
<li class="chapter" data-level="3.3" data-path="chap-probability.html"><a href="chap-probability.html#axioms-and-properties"><i class="fa fa-check"></i><b>3.3</b> Axioms and Properties</a></li>
<li class="chapter" data-level="3.4" data-path="chap-probability.html"><a href="chap-probability.html#sec-probability-counting"><i class="fa fa-check"></i><b>3.4</b> Counting</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="chap-probability.html"><a href="chap-probability.html#product-rule"><i class="fa fa-check"></i><b>3.4.1</b> Product Rule</a></li>
<li class="chapter" data-level="3.4.2" data-path="chap-probability.html"><a href="chap-probability.html#permutations-and-combinations"><i class="fa fa-check"></i><b>3.4.2</b> Permutations and Combinations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chap-probability.html"><a href="chap-probability.html#conditional-probability"><i class="fa fa-check"></i><b>3.5</b> Conditional Probability</a></li>
<li class="chapter" data-level="3.6" data-path="chap-probability.html"><a href="chap-probability.html#independence"><i class="fa fa-check"></i><b>3.6</b> Independence</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html"><i class="fa fa-check"></i><b>4</b> Random Variables and Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#random-variables-1"><i class="fa fa-check"></i><b>4.1</b> Random Variables</a></li>
<li class="chapter" data-level="4.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#probability-functions"><i class="fa fa-check"></i><b>4.2</b> Probability Functions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#probability-mass-function-discrete-rvs"><i class="fa fa-check"></i><b>4.2.1</b> Probability Mass Function (Discrete RVs)</a></li>
<li class="chapter" data-level="4.2.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#chap-rvs-sec-pdf"><i class="fa fa-check"></i><b>4.2.2</b> Probability Density Function (Continuous RVs)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#chap-rvs-sec-cdf"><i class="fa fa-check"></i><b>4.3</b> Cumulative Distribution Function</a></li>
<li class="chapter" data-level="4.4" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#discrete-distributions"><i class="fa fa-check"></i><b>4.4</b> Discrete Distributions</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#binomial-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Binomial Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#distributions-related-to-the-bernoulli"><i class="fa fa-check"></i><b>4.4.2</b> Distributions Related to the Bernoulli</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#continuous-distributions"><i class="fa fa-check"></i><b>4.5</b> Continuous Distributions</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#sec-exponential"><i class="fa fa-check"></i><b>4.5.1</b> Exponential Distribution</a></li>
<li class="chapter" data-level="4.5.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#gamma-distribution"><i class="fa fa-check"></i><b>4.5.2</b> Gamma Distribution</a></li>
<li class="chapter" data-level="4.5.3" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#sec-chi-squared-distribution"><i class="fa fa-check"></i><b>4.5.3</b> Chi-Squared Distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-expected-value.html"><a href="chap-expected-value.html"><i class="fa fa-check"></i><b>5</b> Expected Value</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-expected-value.html"><a href="chap-expected-value.html#expected-value-for-discrete-variables"><i class="fa fa-check"></i><b>5.1</b> Expected Value for Discrete Variables</a></li>
<li class="chapter" data-level="5.2" data-path="chap-expected-value.html"><a href="chap-expected-value.html#expected-value-for-continuous-variables"><i class="fa fa-check"></i><b>5.2</b> Expected Value for Continuous Variables</a></li>
<li class="chapter" data-level="5.3" data-path="chap-expected-value.html"><a href="chap-expected-value.html#expected-value-for-linear-functions"><i class="fa fa-check"></i><b>5.3</b> Expected Value for Linear Functions</a></li>
<li class="chapter" data-level="5.4" data-path="chap-expected-value.html"><a href="chap-expected-value.html#variance-and-standard-deviation-1"><i class="fa fa-check"></i><b>5.4</b> Variance and Standard Deviation</a></li>
<li class="chapter" data-level="5.5" data-path="chap-expected-value.html"><a href="chap-expected-value.html#means-and-variances-of-common-distributions"><i class="fa fa-check"></i><b>5.5</b> Means and Variances of Common Distributions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="chap-expected-value.html"><a href="chap-expected-value.html#binomial"><i class="fa fa-check"></i><b>5.5.1</b> Binomial</a></li>
<li class="chapter" data-level="5.5.2" data-path="chap-expected-value.html"><a href="chap-expected-value.html#hypergeometric"><i class="fa fa-check"></i><b>5.5.2</b> Hypergeometric</a></li>
<li class="chapter" data-level="5.5.3" data-path="chap-expected-value.html"><a href="chap-expected-value.html#negative-binomial"><i class="fa fa-check"></i><b>5.5.3</b> Negative Binomial</a></li>
<li class="chapter" data-level="5.5.4" data-path="chap-expected-value.html"><a href="chap-expected-value.html#poisson"><i class="fa fa-check"></i><b>5.5.4</b> Poisson</a></li>
<li class="chapter" data-level="5.5.5" data-path="chap-expected-value.html"><a href="chap-expected-value.html#exponential"><i class="fa fa-check"></i><b>5.5.5</b> Exponential</a></li>
<li class="chapter" data-level="5.5.6" data-path="chap-expected-value.html"><a href="chap-expected-value.html#gamma"><i class="fa fa-check"></i><b>5.5.6</b> Gamma</a></li>
<li class="chapter" data-level="5.5.7" data-path="chap-expected-value.html"><a href="chap-expected-value.html#chi-squared"><i class="fa fa-check"></i><b>5.5.7</b> Chi-Squared</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="chap-expected-value.html"><a href="chap-expected-value.html#moment-generating-functions"><i class="fa fa-check"></i><b>5.6</b> Moment Generating Functions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html"><i class="fa fa-check"></i><b>6</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#the-normal-and-standard-normal-distributions"><i class="fa fa-check"></i><b>6.1</b> The Normal and Standard Normal Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#chap-non-standard-normal"><i class="fa fa-check"></i><b>6.1.1</b> The Normal Distribution</a></li>
<li class="chapter" data-level="6.1.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#chap-standard-normal"><i class="fa fa-check"></i><b>6.1.2</b> The Standard Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#standardization"><i class="fa fa-check"></i><b>6.2</b> Standardization</a></li>
<li class="chapter" data-level="6.3" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#z-scores"><i class="fa fa-check"></i><b>6.3</b> <span class="math inline">\(z\)</span>-scores</a></li>
<li class="chapter" data-level="6.4" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#probabilities"><i class="fa fa-check"></i><b>6.4</b> Probabilities</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#computing-standard-normal-probabilities"><i class="fa fa-check"></i><b>6.4.1</b> Computing Standard Normal Probabilities</a></li>
<li class="chapter" data-level="6.4.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#computing-normal-probabilities"><i class="fa fa-check"></i><b>6.4.2</b> Computing Normal Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#quantiles"><i class="fa fa-check"></i><b>6.5</b> Quantiles</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#sec-normal-percentiles-visual"><i class="fa fa-check"></i><b>6.5.1</b> Computing Standard Normal Quantiles</a></li>
<li class="chapter" data-level="6.5.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#chap-normal-percentiles"><i class="fa fa-check"></i><b>6.5.2</b> Computing Normal Quantiles</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#sec-QQ-plots"><i class="fa fa-check"></i><b>6.6</b> Q-Q Plots for Checking Normality</a></li>
<li class="chapter" data-level="6.7" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#sec-t-distribution"><i class="fa fa-check"></i><b>6.7</b> t Distribution</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html"><i class="fa fa-check"></i><b>7</b> Joint and Conditional Distributions</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#jointly-distributed-random-variables"><i class="fa fa-check"></i><b>7.1</b> Jointly Distributed Random Variables</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#discrete-random-variables"><i class="fa fa-check"></i><b>7.1.1</b> Discrete Random Variables</a></li>
<li class="chapter" data-level="7.1.2" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#continuous-random-variables"><i class="fa fa-check"></i><b>7.1.2</b> Continuous Random Variables</a></li>
<li class="chapter" data-level="7.1.3" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#more-than-two-random-variables"><i class="fa fa-check"></i><b>7.1.3</b> More Than Two Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#independence-1"><i class="fa fa-check"></i><b>7.2</b> Independence</a></li>
<li class="chapter" data-level="7.3" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#conditional-probability-functions"><i class="fa fa-check"></i><b>7.3</b> Conditional Probability Functions</a></li>
<li class="chapter" data-level="7.4" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#sec-conditional-expectation"><i class="fa fa-check"></i><b>7.4</b> Conditional Expected Values</a></li>
<li class="chapter" data-level="7.5" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#sec-cov-and-corr"><i class="fa fa-check"></i><b>7.5</b> Covariance and Correlation</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#covariance"><i class="fa fa-check"></i><b>7.5.1</b> Covariance</a></li>
<li class="chapter" data-level="7.5.2" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#correlation"><i class="fa fa-check"></i><b>7.5.2</b> Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html"><i class="fa fa-check"></i><b>8</b> Sampling Distributions and Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="8.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#what-is-a-sampling-distribution-and-why-should-you-care"><i class="fa fa-check"></i><b>8.1</b> What Is a Sampling Distribution, and Why Should You Care?</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#preliminary-definitions"><i class="fa fa-check"></i><b>8.1.1</b> Preliminary Definitions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#illustration-via-simulation"><i class="fa fa-check"></i><b>8.2</b> Illustration Via Simulation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#chap-sampling-distributions-sim-normal"><i class="fa fa-check"></i><b>8.2.1</b> Simulation Setup: Normal Population</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sec-distn-sample-mean"><i class="fa fa-check"></i><b>8.3</b> The Distribution of the Sample Mean</a></li>
<li class="chapter" data-level="8.4" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>8.4</b> The Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#simulation-setup-non-normal-population"><i class="fa fa-check"></i><b>8.4.1</b> Simulation Setup: Non-Normal Population</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html"><i class="fa fa-check"></i><b>9</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#introduction"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-pivot-method"><i class="fa fa-check"></i><b>9.2</b> Motivation and Pivots</a></li>
<li class="chapter" data-level="9.3" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-mean"><i class="fa fa-check"></i><b>9.3</b> Confidence Interval for the Population Mean <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-samp-dist-normal"><i class="fa fa-check"></i><b>9.3.1</b> Sampling Distribution conditions</a></li>
<li class="chapter" data-level="9.3.2" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-mean-known-sigma"><i class="fa fa-check"></i><b>9.3.2</b> When <span class="math inline">\(\sigma\)</span> is known (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="9.3.3" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-mean-unknown-sigma"><i class="fa fa-check"></i><b>9.3.3</b> When <span class="math inline">\(\sigma\)</span> is unknown (Using the t Distribution)</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-matchedPairs"><i class="fa fa-check"></i><b>9.4</b> Confidence Interval for Matched Pairs</a></li>
<li class="chapter" data-level="9.5" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-proportion"><i class="fa fa-check"></i><b>9.5</b> Confidence Interval for a Population Proportion (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="9.6" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-variance"><i class="fa fa-check"></i><b>9.6</b> Confidence Interval for a Population Variance (Using the <span class="math inline">\(\chi^2\)</span> Distribution)</a></li>
<li class="chapter" data-level="9.7" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-ci-interpret"><i class="fa fa-check"></i><b>9.7</b> Interpreting a Confidence Interval</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#chap-confidence-intervals-simulation"><i class="fa fa-check"></i><b>9.7.1</b> A Deeper Look at the Idea of Confidence</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-precision-sample-size"><i class="fa fa-check"></i><b>9.8</b> Finding the Sample Size (<span class="math inline">\(n\)</span>) for a Particular Confidence Interval</a></li>
<li class="chapter" data-level="9.9" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#other-types-of-intervals"><i class="fa fa-check"></i><b>9.9</b> Other Types of Intervals</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-ci-prediction"><i class="fa fa-check"></i><b>9.9.1</b> Prediction Intervals</a></li>
<li class="chapter" data-level="9.9.2" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#tolerance-intervals"><i class="fa fa-check"></i><b>9.9.2</b> Tolerance Intervals</a></li>
<li class="chapter" data-level="9.9.3" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>9.9.3</b> Bootstrap Confidence Intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html"><i class="fa fa-check"></i><b>10</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#logic-and-language-of-hypothesis-testing"><i class="fa fa-check"></i><b>10.1</b> Logic and Language of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#chap-ht-definitions"><i class="fa fa-check"></i><b>10.1.1</b> Type I Error, Type II error, and Power</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-test-mean"><i class="fa fa-check"></i><b>10.2</b> Hypothesis Test for a Population Mean</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-mean-known-sigma"><i class="fa fa-check"></i><b>10.2.1</b> When <span class="math inline">\(\sigma\)</span> is known (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="10.2.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-mean-unknown-sigma"><i class="fa fa-check"></i><b>10.2.2</b> When <span class="math inline">\(\sigma\)</span> is unknown (Using the t Distribution)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#hypothesis-test-for-matched-pairs"><i class="fa fa-check"></i><b>10.3</b> Hypothesis Test for Matched Pairs</a></li>
<li class="chapter" data-level="10.4" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-proportion"><i class="fa fa-check"></i><b>10.4</b> Hypothesis Test for a Population Proportion</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#hypothesis-test-for-a-population-variance"><i class="fa fa-check"></i><b>10.4.1</b> Hypothesis Test for a Population Variance</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-one-vs-two"><i class="fa fa-check"></i><b>10.5</b> Two-sided and One-sided Tests</a></li>
<li class="chapter" data-level="10.6" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-power"><i class="fa fa-check"></i><b>10.6</b> Power</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations-for-mu"><i class="fa fa-check"></i><b>10.6.1</b> Power and Sample Size Calculations for <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="10.6.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations"><i class="fa fa-check"></i><b>10.6.2</b> Power and Sample Size Calculations</a></li>
<li class="chapter" data-level="10.6.3" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations-for-chi2"><i class="fa fa-check"></i><b>10.6.3</b> Power and Sample Size Calculations for <span class="math inline">\(\chi^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#exploring-hypothesis-test-via-simulation"><i class="fa fa-check"></i><b>10.7</b> Exploring Hypothesis Test via simulation</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#the-test-statistic-and-its-sampling-distribution-assuming-h_0-is-true"><i class="fa fa-check"></i><b>10.7.1</b> The Test Statistic and its Sampling Distribution: Assuming <span class="math inline">\(H_0\)</span> is true</a></li>
<li class="chapter" data-level="10.7.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#simulation-study-repeated-hypothesis-testing-under-h_0-and-h_a"><i class="fa fa-check"></i><b>10.7.2</b> Simulation Study: Repeated Hypothesis Testing Under <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span></a></li>
<li class="chapter" data-level="10.7.3" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#bootstrap-hypothesis-tests"><i class="fa fa-check"></i><b>10.7.3</b> Bootstrap Hypothesis Tests</a></li>
<li class="chapter" data-level="10.7.4" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#the-basic-bootstrap-hypothesis-test-procedure"><i class="fa fa-check"></i><b>10.7.4</b> The Basic Bootstrap Hypothesis Test Procedure</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap-compare-two.html"><a href="chap-compare-two.html"><i class="fa fa-check"></i><b>11</b> Comparing Two Populations</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-two-sample-means"><i class="fa fa-check"></i><b>11.1</b> Inference on a Difference of Two Population Means</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chap-compare-two.html"><a href="chap-compare-two.html#when-sds-are-known-using-the-normal-distribution"><i class="fa fa-check"></i><b>11.1.1</b> When SDs are Known (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="11.1.2" data-path="chap-compare-two.html"><a href="chap-compare-two.html#when-sds-are-unknown-using-the-t-distribution"><i class="fa fa-check"></i><b>11.1.2</b> When SDs are Unknown (Using the T Distribution)</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-2pop-proportion"><i class="fa fa-check"></i><b>11.2</b> Difference of Two Population Proportions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-2pop-CI-proportion"><i class="fa fa-check"></i><b>11.2.1</b> Confidence Intervals for Two Population Proportions</a></li>
<li class="chapter" data-level="11.2.2" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-2pop-HT-proportion"><i class="fa fa-check"></i><b>11.2.2</b> Hypothesis Tests for Two Population Proportions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="chap-compare-two.html"><a href="chap-compare-two.html#inference-on-a-ratio-of-two-population-variances"><i class="fa fa-check"></i><b>11.3</b> Inference on a Ratio of Two Population Variances</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="chap-compare-more-than-two.html"><a href="chap-compare-more-than-two.html"><i class="fa fa-check"></i><b>12</b> Comparing More Than Two Populations</a></li>
<li class="chapter" data-level="13" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html"><i class="fa fa-check"></i><b>13</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="13.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-model"><i class="fa fa-check"></i><b>13.1</b> The Simple Linear Regression (SLR) Model</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-regression"><i class="fa fa-check"></i><b>13.1.1</b> What Does the Word Regression Mean?</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-least-squares"><i class="fa fa-check"></i><b>13.2</b> The Least Squares Idea</a></li>
<li class="chapter" data-level="13.3" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-assumptions"><i class="fa fa-check"></i><b>13.3</b> Checking the Assumptions</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#good-residuals"><i class="fa fa-check"></i><b>13.3.1</b> Good Residuals</a></li>
<li class="chapter" data-level="13.3.2" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#linearity"><i class="fa fa-check"></i><b>13.3.2</b> Linearity</a></li>
<li class="chapter" data-level="13.3.3" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#constant-variance"><i class="fa fa-check"></i><b>13.3.3</b> Constant Variance</a></li>
<li class="chapter" data-level="13.3.4" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#independence-2"><i class="fa fa-check"></i><b>13.3.4</b> Independence</a></li>
<li class="chapter" data-level="13.3.5" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#normality"><i class="fa fa-check"></i><b>13.3.5</b> Normality</a></li>
<li class="chapter" data-level="13.3.6" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#multiple-assumptions-being-violated"><i class="fa fa-check"></i><b>13.3.6</b> Multiple Assumptions being Violated</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-covariance-correlation"><i class="fa fa-check"></i><b>13.4</b> Covariance, Correlation, and R-squared</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#r-squared"><i class="fa fa-check"></i><b>13.4.1</b> R-squared</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-ci"><i class="fa fa-check"></i><b>13.5</b> Confidence Intervals</a></li>
<li class="chapter" data-level="13.6" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-pi"><i class="fa fa-check"></i><b>13.6</b> Prediction Intervals</a></li>
<li class="chapter" data-level="13.7" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-ht"><i class="fa fa-check"></i><b>13.7</b> Hypothesis Test</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chap-multiple-linear-regression.html"><a href="chap-multiple-linear-regression.html"><i class="fa fa-check"></i><b>14</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="15" data-path="chap-flexible-regression.html"><a href="chap-flexible-regression.html"><i class="fa fa-check"></i><b>15</b> More Flexible Regression Methods</a></li>
<li class="chapter" data-level="16" data-path="chap-categorical-data.html"><a href="chap-categorical-data.html"><i class="fa fa-check"></i><b>16</b> Categorical Data Analysis</a></li>
<li class="chapter" data-level="17" data-path="chap-nonparametrics.html"><a href="chap-nonparametrics.html"><i class="fa fa-check"></i><b>17</b> Nonparametric Methods</a></li>
<li class="chapter" data-level="18" data-path="chap-exercises.html"><a href="chap-exercises.html"><i class="fa fa-check"></i><b>18</b> Exercises</a>
<ul>
<li class="chapter" data-level="18.1" data-path="chap-exercises.html"><a href="chap-exercises.html#foundations"><i class="fa fa-check"></i><b>18.1</b> Foundations</a></li>
<li class="chapter" data-level="18.2" data-path="chap-exercises.html"><a href="chap-exercises.html#probability"><i class="fa fa-check"></i><b>18.2</b> Probability</a></li>
<li class="chapter" data-level="18.3" data-path="chap-exercises.html"><a href="chap-exercises.html#random-variables-and-probability-distributions"><i class="fa fa-check"></i><b>18.3</b> Random Variables and Probability Distributions</a></li>
<li class="chapter" data-level="18.4" data-path="chap-exercises.html"><a href="chap-exercises.html#expected-values"><i class="fa fa-check"></i><b>18.4</b> Expected Values</a></li>
<li class="chapter" data-level="18.5" data-path="chap-exercises.html"><a href="chap-exercises.html#joint-and-conditional-probability"><i class="fa fa-check"></i><b>18.5</b> Joint and Conditional Probability</a></li>
<li class="chapter" data-level="18.6" data-path="chap-exercises.html"><a href="chap-exercises.html#sampling-distributions"><i class="fa fa-check"></i><b>18.6</b> Sampling Distributions</a></li>
<li class="chapter" data-level="18.7" data-path="chap-exercises.html"><a href="chap-exercises.html#principles-of-statistical-inference"><i class="fa fa-check"></i><b>18.7</b> Principles of Statistical Inference</a></li>
<li class="chapter" data-level="18.8" data-path="chap-exercises.html"><a href="chap-exercises.html#confidence-intervals"><i class="fa fa-check"></i><b>18.8</b> Confidence Intervals</a></li>
<li class="chapter" data-level="18.9" data-path="chap-exercises.html"><a href="chap-exercises.html#hypothesis-testing"><i class="fa fa-check"></i><b>18.9</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="18.10" data-path="chap-exercises.html"><a href="chap-exercises.html#comparing-two-populations"><i class="fa fa-check"></i><b>18.10</b> Comparing Two Populations</a></li>
<li class="chapter" data-level="18.11" data-path="chap-exercises.html"><a href="chap-exercises.html#comparing-more-than-two-populations"><i class="fa fa-check"></i><b>18.11</b> Comparing More Than Two Populations</a></li>
<li class="chapter" data-level="18.12" data-path="chap-exercises.html"><a href="chap-exercises.html#linear-regression"><i class="fa fa-check"></i><b>18.12</b> Linear Regression</a></li>
<li class="chapter" data-level="18.13" data-path="chap-exercises.html"><a href="chap-exercises.html#more-flexible-regression-methods"><i class="fa fa-check"></i><b>18.13</b> More Flexible Regression Methods</a></li>
<li class="chapter" data-level="18.14" data-path="chap-exercises.html"><a href="chap-exercises.html#categorical-data-analysis"><i class="fa fa-check"></i><b>18.14</b> Categorical Data Analysis</a></li>
<li class="chapter" data-level="18.15" data-path="chap-exercises.html"><a href="chap-exercises.html#nonparametric-methods"><i class="fa fa-check"></i><b>18.15</b> Nonparametric Methods</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html"><i class="fa fa-check"></i><b>19</b> Appendix: R Tutorial</a>
<ul>
<li class="chapter" data-level="19.1" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#downloading-and-installing-r-and-rstudio"><i class="fa fa-check"></i><b>19.1</b> Downloading and Installing R and RStudio</a></li>
<li class="chapter" data-level="19.2" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-layout-of-rstudio"><i class="fa fa-check"></i><b>19.2</b> The Layout of RStudio</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-source-pane"><i class="fa fa-check"></i><b>19.2.1</b> The Source Pane</a></li>
<li class="chapter" data-level="19.2.2" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-console-pane"><i class="fa fa-check"></i><b>19.2.2</b> The Console Pane</a></li>
<li class="chapter" data-level="19.2.3" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-environments-pane"><i class="fa fa-check"></i><b>19.2.3</b> The Environments Pane</a></li>
<li class="chapter" data-level="19.2.4" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-output-pane"><i class="fa fa-check"></i><b>19.2.4</b> The Output Pane</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#r-basics"><i class="fa fa-check"></i><b>19.3</b> R Basics</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#creating-a-.r-file"><i class="fa fa-check"></i><b>19.3.1</b> Creating a .R file</a></li>
<li class="chapter" data-level="19.3.2" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#saving-your-.r-file"><i class="fa fa-check"></i><b>19.3.2</b> Saving your .R file</a></li>
<li class="chapter" data-level="19.3.3" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#importing-data-into-r-for-analysis"><i class="fa fa-check"></i><b>19.3.3</b> Importing Data into R for Analysis</a></li>
<li class="chapter" data-level="19.3.4" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#coding-in-rstudio"><i class="fa fa-check"></i><b>19.3.4</b> Coding in RStudio</a></li>
<li class="chapter" data-level="19.3.5" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#comments"><i class="fa fa-check"></i><b>19.3.5</b> Comments</a></li>
<li class="chapter" data-level="19.3.6" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#arithmetic-in-r"><i class="fa fa-check"></i><b>19.3.6</b> Arithmetic in R</a></li>
<li class="chapter" data-level="19.3.7" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#variables-and-variable-assignment"><i class="fa fa-check"></i><b>19.3.7</b> Variables and Variable Assignment</a></li>
<li class="chapter" data-level="19.3.8" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#data-types-in-r"><i class="fa fa-check"></i><b>19.3.8</b> Data Types in R</a></li>
<li class="chapter" data-level="19.3.9" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#vectors"><i class="fa fa-check"></i><b>19.3.9</b> Vectors</a></li>
<li class="chapter" data-level="19.3.10" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#logical-operators-in-r"><i class="fa fa-check"></i><b>19.3.10</b> Logical Operators in R</a></li>
<li class="chapter" data-level="19.3.11" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#matrices-in-r"><i class="fa fa-check"></i><b>19.3.11</b> Matrices in R</a></li>
<li class="chapter" data-level="19.3.12" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#factors-in-r"><i class="fa fa-check"></i><b>19.3.12</b> Factors in R</a></li>
<li class="chapter" data-level="19.3.13" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#data-frames-in-r"><i class="fa fa-check"></i><b>19.3.13</b> Data Frames in R</a></li>
<li class="chapter" data-level="19.3.14" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#lists-in-r"><i class="fa fa-check"></i><b>19.3.14</b> Lists in R</a></li>
<li class="chapter" data-level="19.3.15" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#statistics-in-r"><i class="fa fa-check"></i><b>19.3.15</b> Statistics in R</a></li>
<li class="chapter" data-level="19.3.16" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#visualizations-in-r"><i class="fa fa-check"></i><b>19.3.16</b> Visualizations in R</a></li>
<li class="chapter" data-level="19.3.17" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#downloading-and-using-packages-in-r"><i class="fa fa-check"></i><b>19.3.17</b> Downloading and Using Packages in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="chap-glossary.html"><a href="chap-glossary.html"><i class="fa fa-check"></i><b>20</b> Glossary</a>
<ul>
<li class="chapter" data-level="20.1" data-path="chap-glossary.html"><a href="chap-glossary.html#overview"><i class="fa fa-check"></i><b>20.1</b> Overview</a></li>
<li class="chapter" data-level="20.2" data-path="chap-glossary.html"><a href="chap-glossary.html#foundations-1"><i class="fa fa-check"></i><b>20.2</b> Foundations</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions"><i class="fa fa-check"></i><b>20.2.1</b> Definitions</a></li>
<li class="chapter" data-level="20.2.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands"><i class="fa fa-check"></i><b>20.2.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="chap-glossary.html"><a href="chap-glossary.html#probability-1"><i class="fa fa-check"></i><b>20.3</b> Probability</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-1"><i class="fa fa-check"></i><b>20.3.1</b> Definitions</a></li>
<li class="chapter" data-level="20.3.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-1"><i class="fa fa-check"></i><b>20.3.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="chap-glossary.html"><a href="chap-glossary.html#random-variables-and-probability-distributions-1"><i class="fa fa-check"></i><b>20.4</b> Random Variables and Probability Distributions</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-2"><i class="fa fa-check"></i><b>20.4.1</b> Definitions</a></li>
<li class="chapter" data-level="20.4.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-2"><i class="fa fa-check"></i><b>20.4.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="chap-glossary.html"><a href="chap-glossary.html#expected-value"><i class="fa fa-check"></i><b>20.5</b> Expected Value</a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-3"><i class="fa fa-check"></i><b>20.5.1</b> Definitions</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="chap-glossary.html"><a href="chap-glossary.html#the-normal-distribution"><i class="fa fa-check"></i><b>20.6</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-4"><i class="fa fa-check"></i><b>20.6.1</b> Definitions</a></li>
<li class="chapter" data-level="20.6.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-3"><i class="fa fa-check"></i><b>20.6.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.7" data-path="chap-glossary.html"><a href="chap-glossary.html#joint-and-conditional-distributions"><i class="fa fa-check"></i><b>20.7</b> Joint and Conditional Distributions</a>
<ul>
<li class="chapter" data-level="20.7.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-5"><i class="fa fa-check"></i><b>20.7.1</b> Definitions</a></li>
</ul></li>
<li class="chapter" data-level="20.8" data-path="chap-glossary.html"><a href="chap-glossary.html#sampling-distributions-and-central-limit-theorem"><i class="fa fa-check"></i><b>20.8</b> Sampling Distributions and Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="20.8.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-6"><i class="fa fa-check"></i><b>20.8.1</b> Definitions</a></li>
<li class="chapter" data-level="20.8.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-4"><i class="fa fa-check"></i><b>20.8.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.9" data-path="chap-glossary.html"><a href="chap-glossary.html#confidence-intervals-1"><i class="fa fa-check"></i><b>20.9</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="20.9.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-7"><i class="fa fa-check"></i><b>20.9.1</b> Definitions</a></li>
<li class="chapter" data-level="20.9.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-5"><i class="fa fa-check"></i><b>20.9.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.10" data-path="chap-glossary.html"><a href="chap-glossary.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>20.10</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="20.10.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-8"><i class="fa fa-check"></i><b>20.10.1</b> Definitions</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Probability and Statistics: Making Principled Decisions in an Uncertain World</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-foundations" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Foundations<a href="chap-foundations.html#chap-foundations" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="what-is-statistics" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> What is Statistics?<a href="chap-foundations.html#what-is-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Statistics is often described as "the art and science of data." It is a set of tools for answering scientific questions of interest.</p>
<p>As a science, statistics relies on mathematical principles, empirical methods, and formalized procedures. It provides tools for collecting, analyzing, interpreting, presenting, and organizing data, using a systematic approach grounded in mathematical theory. From hypothesis testing to regression analysis, the scientific side of statistics offers structured ways to make inferences, draw conclusions, and make predictions based on data.</p>
<p>But statistics is also an art, requiring creativity, intuition, and a thoughtful consideration of context. The art of statistics lies in the ability to ask meaningful questions, design insightful studies, and communicate findings in an engaging and understandable way. It is about selecting the right method for the situation, making thoughtful assumptions, recognizing patterns and nuances in data, and telling a compelling story through numbers.</p>
<p>In this interplay between art and science, statistics becomes a powerful discipline that transcends mere numbers. It helps us to understand the world around us, informing decisions in fields as diverse as medicine, economics, politics, sports, and beyond. Whether you are a researcher unraveling the mysteries of a disease, a policy-maker seeking evidence for social interventions, or a business leader making data-driven decisions, statistics provides a framework that combines logical reasoning with creative thinking.</p>
<p>In this book, we will explore both the art and science of data, unlocking the tools and insights that make statistics such an indispensable field of study. Through real-life examples, hands-on exercises, and engaging visuals, we will uncover the beauty and complexity that lies at the heart of statistics.</p>
</div>
<div id="populations-and-parameters-samples-and-statistics" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Populations and Parameters, Samples and Statistics<a href="chap-foundations.html#populations-and-parameters-samples-and-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In Statistics, we are interested in studying a particular <strong>population</strong>. This population encompasses the entire collection of people, animals, objects, or entities that are the focus of our investigation. These objects are generically referred to as <strong>units</strong>. Whether we are investigating the heights of all students at a university, the survival times of all people with a disease, or the attitudes of citizens in a country, the population is the complete set of what we aim to study.</p>
<p>Within the population, there is typically a specific numerical characteristic that we are interested in, called a <strong>parameter</strong>. The parameter is a value that summarizes a particular aspect of the population. For instance, the average height of all students, the median survival time after diagnosis of people with a disease, or the percentage of individuals with a specific opinion in a survey are all examples of parameters. In order to compute the value of a parameter, we would have to observe every single member of the population. This is never possible in any realistic application.</p>
<p>In practice, since it is not possible to observe the entire population, we draw a <strong>sample</strong> from the population. A sample is a smaller subset of individuals or items selected with care to represent the population as a whole. For example, we might select 1,000 students from the current roster of all students at a university, enroll 100 diseased people who are seen at a hospital, or contact 100,000 citizens with an online survey. By studying the sample, our goal is to learn about the population.</p>
<p>Using a sample, we can estimate the parameter of interest by computing a <strong>statistic</strong>. A statistic is simply a number that we compute based on sample data. For example, we could compute the average height of our 1,000 sampled students, the median survival time after diagnosis of our 100 sampled patients, or the proportion of our 100,000 sampled citizens who respond a particular way to a survey question.</p>
<p><em>Note</em>: We are intentionally glossing over one technical point; namely, for the purposes of this book, we will assume that the population is <em>infinite</em>. That is, when taking a sample from a population, we do not worry about changes to the composition of the population due to some of its (finite) individuals being sampled. If the population consists of a finite collection of individuals, then, as we sample some of those individuals, there are impacts on our resulting dataset and downstream statistical analysis. As a result, much of the methodology that will be presented in what follows would need special treatment. To keep our presentation simple and broadly applicable, we avoid these technical issues and proceed under the standard assumption of an infinite (or effectively infinite) population.</p>
</div>
<div id="obtaining-data" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Obtaining Data<a href="chap-foundations.html#obtaining-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In Statistics, <strong>data</strong> is the raw material from which we derive insights, make informed decisions, and reveal hidden patterns. Everything a statistician does, whether it's constructing models, drawing conclusions, or making predictions, is rooted in data. Therefore, the process of <em>obtaining</em> data is critical.</p>
<p>Since we are interested in a particular population (and one or more associated parameters), the data we gather should be <em>representative of</em> the characteristics of that population. By "representative of", we simply mean that our sample data should not differ from the population in any systematic way. Otherwise, any lessons we learn from analyzing our data cannot be generalized to the population.</p>
<p>As discussed in more detail in Section <a href="chap-foundations.html#sec-foundations-nature-of-data">2.4</a>, we will generically refer to a dataset as an array with <strong>individuals</strong> (the people, animals, objects, or entities we have observed) in the rows and <strong>variables</strong> (the people, animals, objects, or entities we have observed) in the columns.</p>
<div id="chap-foundations-sampling" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Sampling<a href="chap-foundations.html#chap-foundations-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Given a population of individuals, there are a variety of <strong>sampling</strong> strategies we can employ for selecting individuals into a sample.</p>
<p><strong>Simple random sampling</strong> involves selecting a random subset of individuals from the population. Each individual has an equal chance of being chosen, which helps mitigate bias and ensures that every potential participant has a chance to contribute. Simple random sampling is a foundational technique that facilitates unbiased estimation of population parameters.</p>
<p><strong>Stratified sampling</strong> is used when we want to account for different subgroups within the population. The population is divided into distinct strata based on specific characteristics (e.g., race, education level, age group), and then samples are drawn from each stratum. This approach ensures that each subgroup is represented and allows us to control for important sources of variation.</p>
<p><strong>Cluster sampling</strong> involves selecting groups or "clusters" of related individuals. The population is divided into clusters (e.g., households, geographic regions, time periods), and a subset of clusters are randomly selected. Data are then collected from all members within the selected clusters. Cluster sampling is particularly useful when logistical constraints limit access to individual participants.</p>
<p>When <strong>sampling with replacement</strong>, each selected unit is returned to the population before the next selection. This allows for the possibility of selecting the same unit more than once. <strong>Sampling without replacement</strong>, on the other hand, ensures that each unit can be selected only once. The choice between these methods depends on the context and the impact of potential duplicates.</p>
<p>Not all data collection methods ensure representative samples. For example, a <strong>convenience sample</strong> is composed of readily available participants and may not accurately reflect the broader population. Similarly, samples resulting from <strong>self-selection</strong>, where individuals choose to participate, can introduce biases that affect the validity of the findings. Recognizing the limitations of such samples is crucial when interpreting results.</p>
</div>
<div id="chap-foundations-observational-experiment" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Observational Studies and Experiments<a href="chap-foundations.html#chap-foundations-observational-experiment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are two main types of studies that can be used to generate data: <strong>observational studies</strong> and <strong>experiments</strong>.</p>
<p>In an observational study, we simply observe and record data. There is no intervention of the study, and there is no manipulation of the variables. This approach helps us uncover relationships, correlations, and patterns that naturally exist within the data. However, it is important to recognize that while observational studies can identify associations, they generally cannot establish causation. This limitation arises from the possibility of <strong>lurking variables</strong> -- unaccounted-for factors that may influence both the observed variables and the outcome.</p>
<p>As an example of an observational study, suppose we obtain data on weekly sales of ice cream and the number of drownings at public beaches in the U.S. If we were to plot such data (for example, with ice cream sales in dollars on the horizontal axis and number of drownings on the vertical axis), we would likely see an increasing trend, suggesting that ice cream sales are <strong>positively correlated</strong> with drownings; we will define the statistical concept of <strong>correlation</strong> in Chapter <a href="chap-joint-conditional.html#chap-joint-conditional">7</a>. However, suppose we also collected data on the average weekly <em>temperature</em> at the beaches we sampled. If we plotted temperature vs. drownings, we would likely see that they are also positively correlated. In fact, it is likely that temperature is a much more important factor for explaining drownings than ice cream sales. Both ice cream sales and drownings are likely impacted by temperature. We would say in this case that ice cream sales and temperature are <strong>confounded</strong> (it is hard to separate the influence of one variable from the influence of the other) and that temperature is a lurking variable. We would certainly be incorrect in stating that increased ice cream sales <em>cause</em> more drownings.</p>
<p>In contrast to observational studies, experiments involve deliberate manipulation of variables to assess their impact on an outcome. By randomly assigning subjects to different conditions, we aim to establish causal relationships between variables. When carefully designed, experiments enable us to draw conclusions about cause and effect as they provide more control over the factors at play.</p>
<p>In the context of the drownings example, a possible experiment would be to randomly assign a sample of beach-goers to consume varying amounts of ice cream and then record whether each of them drowns. Suppose that we were also able to enforce that all other relevant factors (e.g., temperature, gender, age, swimming ability, etc.) did not vary in any systematic way across the different ice cream "treatment" levels, to the extent that the <em>only</em> source of systematic variation among the study participants was the amount of ice cream consumed. Obviously, this would be very complicated to pull off in practice. Nevertheless, such an idealized experiment <em>would</em> allow us to speak to whether increased ice cream consumption causes more drownings.</p>
</div>
</div>
<div id="sec-foundations-nature-of-data" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> The Nature of Data<a href="chap-foundations.html#sec-foundations-nature-of-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A dataset ultimately can be boiled down to an array (e.g., a spreadsheet) full of numbers and characters. We will generally organize data such that <strong>individuals</strong> (the people, animals, objects, or entities we have observed) are in the rows, and <strong>variables</strong> (the things we have recorded or measured, like an individual's age, or income, or survival time) are in the columns.</p>
<p>Variables can be characterized as either <strong>quantitative</strong> (also called <strong>numeric</strong>) or <strong>qualitative</strong> (also called <strong>categorical</strong>). Quantitative variables take numbers as values, and you can do arithmetic with them. The height of a student in inches and the survival time in months of a diseased person are both examples of quantitative variables. Qualitative variables, on the other hand, represent qualities or characteristics that place observations into different groups or categories. An example of a qualitative variable would be a survey respondent's race. It does not make sense to do arithmetic with a qualitative variable; this is true even if the variable takes values that are represented by numbers, such as ZIP code.</p>
<p>Quantitative variables can be further characterized as being either <strong>discrete</strong> or <strong>continuous</strong>. Discrete quantitative variables can only assume specific, separate values within a range. These values are often counted or enumerated and are distinct from one another. Examples include the number of students in a class or the count of defects in a production batch. Continuous quantitative variables can take an infinite number of values within a specified range. They are often associated with measurements that can be infinitely subdivided. Examples include height, weight, and time.</p>
<p>Qualitative variables can be sub-typed into <strong>nominal</strong> or <strong>ordinal</strong>. Nominal, which literally means name, indicates that the categories have no imposable order. Examples of this would be the aforementioned ZIP code or your UIN. Ordinal would be a qualitative variable whose categories have a naturally imposable order. An example would be if we surveyed a group of individuals on their smart phone usage and allowed the following responses describing how often they use their phone: never, occasionally, regularly, frequently, and nearly constant.</p>
<div id="randomness-and-uncertainty" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Randomness and Uncertainty<a href="chap-foundations.html#randomness-and-uncertainty" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Randomness</strong> (unpredictable variation from one case to the next) is a major theme of Statistics. In particular, there is usually some amount of randomness involved in the process of collecting our sample data. For example, suppose we are studying the heights of students on campus, and we collect a sample of 1,000 students by randomly selecting names from the roster of all current students. Anything we observe in our sample is now subject to randomness. If we were to repeat the process, collecting an entirely new random sample of 1,000 students, our observations would change somewhat. Thus, at the end of any statistical exercise, we are forced to acknowledge the role that randomness played in affecting our observations and the fact that repeating the exercise would surely result in different observations.</p>
<p>One of the core objectives of Statistics is to estimate the level of <strong>uncertainty</strong> that should be assigned to estimates we form or decisions we make on the basis of a data analysis. <strong>Statistical inference</strong> involves using sample data to draw confident conclusions about a population. For example, a <strong>confidence interval</strong> is a range of values that is expected to contain a population parameter with a stated level of "confidence". For example, we might say something like "I am 95% confident that the average height in inches of current Texas A&amp;M University students is between 67.2 and 68.1 inches." A <strong>hypothesis test</strong> involves making a formal decision about the value of a population parameter, with a stated level of confidence. For example, we might say something like "I am 95% confident that the average height in inches of current Texas A&amp;M University students is not less than 60 inches." What we mean exactly by these inferential statements requires substantially more background to explain; we will explore confidence intervals in Chapter <a href="chap-confidence-intervals.html#chap-confidence-intervals">9</a> and hypothesis tests in Chapter <a href="chap-hypothesis-testing.html#chap-hypothesis-testing">10</a>.</p>
</div>
<div id="random-variables" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Random Variables<a href="chap-foundations.html#random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>random variable</strong> is a variable whose value is subject to randomness. Random variables can be quantitative or qualitative, and quantitative random variables can be discrete or continuous. We will use <strong>probability</strong> as a mathematical framework for quantifying the likelihoods that a random variable takes possible values. We will describe the collection of all possible values of a random variable and the probabilities associated with these values as the variable's <strong>distribution</strong>. A distribution can be characterized in terms of its <strong>location</strong> (referring to what values are "typical"), <strong>spread</strong> (referring to how much variability there is in the values it takes), and <strong>shape</strong> (referring to various characteristics, e.g. whether a distribution is "symmetric", with big values just as likely as small values, or "skewed" where one side is more likely).</p>
</div>
<div id="notation" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Notation<a href="chap-foundations.html#notation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will frequently use mathematical notation to represent variables. For example, beginning in Chapter <a href="chap-probability.html#chap-probability">3</a>, we will use <span class="math inline">\(X\)</span> (or <span class="math inline">\(Y\)</span> or <span class="math inline">\(Z\)</span>) to represent a generic random variable. When talking theoretically about a sample of observations of a random variable, we will use <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> to represent the 1st, 2nd, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(n\)</span>th observation, respectively, where <span class="math inline">\(n\)</span> indicates the size of the sample. When talking about actually observed values (after running the experiment or observing the process), we will use lower-case notation like <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span>.</p>
<p>Consider a <strong>dataset</strong>, which, again, you can think of as a spreadsheet with individuals in the rows and variables in the columns. We might use notation like <span class="math inline">\(x_j\)</span> to refer to the <span class="math inline">\(j\)</span>th variable (column) and <span class="math inline">\(x_{ij}\)</span> to refer to the <span class="math inline">\(i\)</span>th observation (row) of the <span class="math inline">\(j\)</span>th variable.</p>
<p>Beginning in Chapter <a href="chap-simple-linear-regression.html#chap-simple-linear-regression">13</a>, we will talk about modeling / explaining one variable (called the <strong>response variable</strong>) in terms of one or more <strong>explanatory variables</strong>; a response variable is sometimes called a <strong>dependent variable</strong>, and an explanatory variable is sometimes called an <strong>independent variable</strong>. We will use <span class="math inline">\(y\)</span> to represent a response variable and <span class="math inline">\(x_1, x_2, \ldots, x_p\)</span> to represent a collection of <span class="math inline">\(p\)</span> explanatory variables. Given a sample of such data, we will say that <span class="math inline">\(y_i\)</span> is the observed value of the response variable, and <span class="math inline">\(x_{i1}, x_{i2}, \ldots, x_{ip}\)</span> are the observed values of the explanatory variables for the <span class="math inline">\(i\)</span>th individual in our sample, for any <span class="math inline">\(i = 1, 2, \ldots, n\)</span>.</p>
</div>
</div>
<div id="numerical-summaries" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Summary Statistics<a href="chap-foundations.html#numerical-summaries" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will now consider our first dataset. The <code>PlantGrowth</code> dataset is part of the <code>R</code> package <code>datasets</code>. As such, we can access it with the <code>data</code> command:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="chap-foundations.html#cb1-1" tabindex="-1"></a><span class="fu">require</span>(datasets)</span>
<span id="cb1-2"><a href="chap-foundations.html#cb1-2" tabindex="-1"></a><span class="fu">data</span>(PlantGrowth)</span>
<span id="cb1-3"><a href="chap-foundations.html#cb1-3" tabindex="-1"></a></span>
<span id="cb1-4"><a href="chap-foundations.html#cb1-4" tabindex="-1"></a><span class="co"># Structural summary of the R object</span></span>
<span id="cb1-5"><a href="chap-foundations.html#cb1-5" tabindex="-1"></a><span class="fu">str</span>(PlantGrowth) </span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  2 variables:
##  $ weight: num  4.17 5.58 5.18 6.11 4.5 4.61 5.17 4.53 5.33 5.14 ...
##  $ group : Factor w/ 3 levels &quot;ctrl&quot;,&quot;trt1&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="chap-foundations.html#cb3-1" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb3-2"><a href="chap-foundations.html#cb3-2" tabindex="-1"></a><span class="fu">head</span>(PlantGrowth) </span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">weight</th>
<th align="left">group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">4.17</td>
<td align="left">ctrl</td>
</tr>
<tr class="even">
<td align="right">5.58</td>
<td align="left">ctrl</td>
</tr>
<tr class="odd">
<td align="right">5.18</td>
<td align="left">ctrl</td>
</tr>
<tr class="even">
<td align="right">6.11</td>
<td align="left">ctrl</td>
</tr>
<tr class="odd">
<td align="right">4.50</td>
<td align="left">ctrl</td>
</tr>
<tr class="even">
<td align="right">4.61</td>
<td align="left">ctrl</td>
</tr>
</tbody>
</table>
</div>
<p>The <code>str</code> function displays structural information of an <code>R</code> object. In the case of <code>PlantGrowth</code>, we see that it is a data frame with <span class="math inline">\(n = 30\)</span> observations of two variables, <code>weight</code> (numeric) and <code>group</code> (factor, with three "levels" or categories); note that <code>R</code> uses the <code>factor</code> class to represent qualitative variables. We can use the <code>head</code> function to take a peek at the first few rows of the data frame. We can obtain additional documentation on this dataset with <code>? PlantData</code>. From the documentation file, we learn that these data are results from an experiment to compare yields (as measured by dried weight of plants) obtained under a control and two different treatment conditions.</p>
<p>We can access each variable using the $ symbol, or we can use the <code>attach</code> function to attach all variables to the working directory, enabling us to call variables directly using just their names.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="chap-foundations.html#cb4-1" tabindex="-1"></a>PlantGrowth<span class="sc">$</span>weight</span></code></pre></div>
<pre><code>##  [1] 4.17 5.58 5.18 6.11 4.50 4.61 5.17 4.53 5.33 5.14 4.81 4.17 4.41 3.59 5.87
## [16] 3.83 6.03 4.89 4.32 4.69 6.31 5.12 5.54 5.50 5.37 5.29 4.92 6.15 5.80 5.26</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="chap-foundations.html#cb6-1" tabindex="-1"></a><span class="do">## Attach the variables to the working directory</span></span>
<span id="cb6-2"><a href="chap-foundations.html#cb6-2" tabindex="-1"></a><span class="fu">attach</span>(PlantGrowth)</span>
<span id="cb6-3"><a href="chap-foundations.html#cb6-3" tabindex="-1"></a>weight</span></code></pre></div>
<pre><code>##  [1] 4.17 5.58 5.18 6.11 4.50 4.61 5.17 4.53 5.33 5.14 4.81 4.17 4.41 3.59 5.87
## [16] 3.83 6.03 4.89 4.32 4.69 6.31 5.12 5.54 5.50 5.37 5.29 4.92 6.15 5.80 5.26</code></pre>
<div id="mean" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Mean<a href="chap-foundations.html#mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are many ways to summarize a quantitative variable in terms of its "typical values." The most common summary statistic used is the <strong>sample mean</strong>. Let <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> be the observed values of a quantitative variable. The sample mean is the simple arithmetic average of the <span class="math inline">\(x_i\)</span>. We will use the notation <span class="math inline">\(\bar{x}\)</span> for the sample mean:
<span class="math display">\[
\bar{x} = \frac{1}{n} \sum_{i=1}^n x_i
\]</span></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="chap-foundations.html#cb8-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(PlantGrowth)</span>
<span id="cb8-2"><a href="chap-foundations.html#cb8-2" tabindex="-1"></a><span class="fu">sum</span>(weight) <span class="sc">/</span> n <span class="do">## Compute manually</span></span></code></pre></div>
<pre><code>## [1] 5.073</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="chap-foundations.html#cb10-1" tabindex="-1"></a><span class="fu">mean</span>(weight) <span class="do">## Now use &#39;mean&#39; function</span></span></code></pre></div>
<pre><code>## [1] 5.073</code></pre>
<p>The sample mean, <span class="math inline">\(\bar{X}\)</span>, is a sample statistic. We use it as an estimate of the population mean, a parameter. We will use the Greek symbol <span class="math inline">\(\mu\)</span> to represent a population mean. You can think of the population mean as the arithmetic average of all values in the population. We will define population means in detail using probability distributions and <strong>expected values</strong> in Chapter <a href="chap-expected-value.html#chap-expected-value">5</a>.</p>
</div>
<div id="sec-percentiles-median" class="section level3 hasAnchor" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Percentiles and Median<a href="chap-foundations.html#sec-percentiles-median" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <span class="math inline">\(p\)</span>th <strong>sample percentile</strong> is the number that separates the lowest <span class="math inline">\(p\%\)</span> of the sample observations from the largest <span class="math inline">\((100 - p)\%\)</span> observations. For example, if a student scores in the 90th percentile on a test, then <span class="math inline">\(90\%\)</span> of the people taking the exam scored less than the student. The <strong>sample median</strong> (<span class="math inline">\(\tilde{x}\)</span>) is the 50th percentile and can therefore be thought of as the "middle" value. The 25th percentile is called the <strong>first quartile</strong> (<span class="math inline">\(Q1\)</span>), and the 75th percentile is called the <strong>third quartile</strong> (<span class="math inline">\(Q3\)</span>); the median is also called the <strong>second quartile</strong> (<span class="math inline">\(Q2\)</span>). The <strong>interquartile range</strong> (IQR) is the difference between the 75th and 25th percentiles (<span class="math inline">\(Q3 - Q1\)</span>) and therefore characterizes the inner 50% of a distribution of data.</p>
<p>There are many definitions of a sample percentile (and hence of the sample median). The default version of the <code>R</code> function <code>quantile</code> calculates sample percentiles by linearly interpolating between adjacent data points in the sorted sample. Seeing this applied to the plant growth data set:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chap-foundations.html#cb12-1" tabindex="-1"></a><span class="do">## Use &#39;quantile&#39; to compute Q1, Q2, and Q3. Compare with &#39;median&#39;.</span></span>
<span id="cb12-2"><a href="chap-foundations.html#cb12-2" tabindex="-1"></a><span class="fu">quantile</span>(weight, <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>))</span></code></pre></div>
<pre><code>##   25%   50%   75% 
## 4.550 5.155 5.530</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="chap-foundations.html#cb14-1" tabindex="-1"></a><span class="fu">median</span>(weight)</span></code></pre></div>
<pre><code>## [1] 5.155</code></pre>
<p>The <code>summary</code> function returns the sample mean and a <strong>five number summary</strong> consisting of <span class="math inline">\(\min, Q1, \tilde{x}, Q3, \max\)</span>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chap-foundations.html#cb16-1" tabindex="-1"></a><span class="fu">summary</span>(weight)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.590   4.550   5.155   5.073   5.530   6.310</code></pre>
<p>There are of course population parameter versions of percentiles. We will define them in terms of <strong>cumulative distribution functions</strong> in Chapter <a href="chap-rvs-distributions.html#chap-rvs-distributions">4</a>.</p>
</div>
<div id="variance-and-standard-deviation" class="section level3 hasAnchor" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Variance and Standard Deviation<a href="chap-foundations.html#variance-and-standard-deviation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The mean and median characterize what is a "typical value" for a variable. We can also think of them as characterizing the "location" of a dataset or distribution. Another important characteristic of a variable is its "spread" or "variability." For example, consider a variable <span class="math inline">\(x\)</span> with values <span class="math inline">\(-1, 0, 1\)</span> and another variable <span class="math inline">\(y\)</span> with values <span class="math inline">\(-10, 0, 10\)</span>. Both variables have the same sample mean (0) and sample median (also 0), but <span class="math inline">\(y\)</span> is more spread out / more variable.</p>
<p>The most common summary statistics used to characterize spread are the <strong>sample variance</strong> (<span class="math inline">\(s^2\)</span>):
<span class="math display">\[
s^2 = \frac{1}{n-1} \sum_{i=1}^n \left( x_i - \bar{x} \right) ^ 2
\]</span>
and the sample standard deviation <span class="math inline">\(s = \sqrt{s^2}\)</span> (the positive square root). Note that <span class="math inline">\(s^2\)</span> is a kind of average; it is the sum of the <span class="math inline">\(n\)</span> squared differences between individual observations and the sample mean that is then divided by <span class="math inline">\((n-1)\)</span> (as for why it is <span class="math inline">\((n-1)\)</span> is discussed with sample distributions). Thus, we can think of the variance as an "average" squared difference between observed values and the sample average. If data values are highly spread out, the sum will include some large squared differences, making the variance large.</p>
<p>We can use the <code>var</code> function to compute a sample variance. The variance of <span class="math inline">\(x_1\)</span> is <span class="math inline">\(1\)</span>, and the variance of <span class="math inline">\(x_2\)</span> is <span class="math inline">\(100\)</span>. Note that there is also a function <code>sd</code> for computing the sample standard deviation.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chap-foundations.html#cb18-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb18-2"><a href="chap-foundations.html#cb18-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb18-3"><a href="chap-foundations.html#cb18-3" tabindex="-1"></a></span>
<span id="cb18-4"><a href="chap-foundations.html#cb18-4" tabindex="-1"></a><span class="do">## Same mean and median</span></span>
<span id="cb18-5"><a href="chap-foundations.html#cb18-5" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="do">## Assign to a variable so we can use it later</span></span>
<span id="cb18-6"><a href="chap-foundations.html#cb18-6" tabindex="-1"></a>x_bar</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chap-foundations.html#cb20-1" tabindex="-1"></a><span class="fu">median</span>(x)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chap-foundations.html#cb22-1" tabindex="-1"></a><span class="fu">mean</span>(y)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chap-foundations.html#cb24-1" tabindex="-1"></a><span class="fu">median</span>(y)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chap-foundations.html#cb26-1" tabindex="-1"></a><span class="do">## Different variance and sd</span></span>
<span id="cb26-2"><a href="chap-foundations.html#cb26-2" tabindex="-1"></a><span class="fu">sum</span>((x <span class="sc">-</span> x_bar) <span class="sc">^</span> <span class="dv">2</span>) <span class="sc">/</span> (<span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="do">## Compute manually</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chap-foundations.html#cb28-1" tabindex="-1"></a><span class="fu">var</span>(x)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="chap-foundations.html#cb30-1" tabindex="-1"></a><span class="fu">sd</span>(x)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="chap-foundations.html#cb32-1" tabindex="-1"></a><span class="fu">var</span>(y)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="chap-foundations.html#cb34-1" tabindex="-1"></a><span class="fu">sd</span>(y)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>Note that, while the unit of measurement for <span class="math inline">\(s^2\)</span> is the square of the units original, the unit of measurement for <span class="math inline">\(s\)</span> is the same as those of the original variable; this makes the standard deviation a more interpretable quantity than the variance. For example, if we are measuring people's income in the United States, the sample variance would be in units of <span class="math inline">\(\$^2\)</span> while the sample standard deviation would be in units of $.</p>
</div>
<div id="extreme-values-and-robust-statistics" class="section level3 hasAnchor" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> Extreme Values and Robust Statistics<a href="chap-foundations.html#extreme-values-and-robust-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An important distinguishing characteristic of the mean is that it is sensitive to extreme values, whereas the median is not. As an example, consider what happens if we replace one of the values of the <code>weight</code> variable with an extreme value in our plant dataset. We will replace the first value (originally 4.17) with the value 100 and re-compute the mean and median:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="chap-foundations.html#cb36-1" tabindex="-1"></a>weight_star <span class="ot">&lt;-</span> weight</span>
<span id="cb36-2"><a href="chap-foundations.html#cb36-2" tabindex="-1"></a>weight_star[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb36-3"><a href="chap-foundations.html#cb36-3" tabindex="-1"></a><span class="fu">mean</span>(weight_star)</span></code></pre></div>
<pre><code>## [1] 8.267333</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="chap-foundations.html#cb38-1" tabindex="-1"></a><span class="fu">median</span>(weight_star)</span></code></pre></div>
<pre><code>## [1] 5.175</code></pre>
<p>The mean has gone from 5.073 all the way up to 8.267, but the median is unchanged. The mean is affected in this way because it involves the sum of all individual values. If one or more of the individual values is "extreme," the sum (and therefore the mean) is going to be pulled in the direction of the extreme values. The median, on the other hand, is based on <em>ranks</em>, not <em>values</em>. Changing the value of one or even a few observations will have little effect on where the middle value is located. We say that the median is <strong>robust</strong> to extreme values and the mean is not.</p>
<p>There are common scenarios in which we might prefer the median over the mean. Suppose, for example, that our goal is to characterize a "typical value" of annual household income in a particular country. The vast majority of households likely have annual incomes that fall within a regular distribution of values. There would be a minority who earn very little, a minority who earn a lot, and the majority would fall somewhere in the middle. However, there is no upper bound on annual income, and there would likely be a tiny subset of "elites" with extremely high incomes that are "off the charts" compared to everyone else. The mean would be pulled in the direction of the extreme values, resulting in an estimated typical value that is arguably not reflective of the reality for the typical household. For this reason, the median would arguably be the more appropriate summary.</p>
<p>Note that the standard deviation is also sensitive to extreme values, since, like the mean, it is a kind of average; in addition, the standard deviation involves <em>squared</em> values, so extremes are especially influential. IQR is a robust alternative to the standard deviation. Like the median, IQR is based on ranks rather than values, so it is not as sensitive to extremes. Changing the first observation of the <code>weight</code> variable as above, resulted in the standard deviation going from 0.7012 to 17.3389, but the IQR barely changed, going from 0.98 to 0.94. In general, we will tend to use the mean and standard deviation to characterize typical values and variability, respectively. In the presence of extreme values or skewness (see below), we may choose to instead use the median and IQR.</p>
<p>An <strong>extreme value</strong> (frequently referred to as an <strong>outlier</strong>, though typically the word outlier connotes that it doesn't belong) is a value for a variable that is very different from other values. There is no precise definition for what constitutes an extreme value, although there are some rules of thumb. One common rule for flagging an observation as a potential extreme value is based on IQR. The rule is that an observation is a potential extreme value if it is greater than <span class="math inline">\(Q3 + 1.5 \times \text{IQR}\)</span> or less than <span class="math inline">\(Q1 - 1.5 \times \text{IQR}\)</span>.</p>
<p>One important practical consideration when conducting a data analysis is what to do with any extreme values. Consider again, for example, the <code>weight</code> variable. Our modification of the first observation (changing it from 4.17 to 100) would result in that value being flagged as a possible extreme value by the above rule of thumb. Upon further investigation, we would likely conclude that it is not feasible for one of our plant samples to have weighed 100 pounds. We might reasonably then conclude that this weight measurement was erroneous and remove it from the dataset. However, in general, there is not necessarily anything <em>wrong</em> with extreme values. With household annual income, for example, it would be unusual, but not impossible, to observe millions (if not billions) of dollars. While we might choose to use robust statistics to minimize the influence of extreme values, we should not be quick to <em>remove</em> observations just because they are outliers; doing so could actually bias our conclusions.</p>
</div>
<div id="frequency-and-relative-frequency" class="section level3 hasAnchor" number="2.5.5">
<h3><span class="header-section-number">2.5.5</span> Frequency and Relative Frequency<a href="chap-foundations.html#frequency-and-relative-frequency" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To summarize a qualitative variable, we simply count the number of instances of each of its categories. The <strong>frequency</strong> of a particular category (a category is also called a <strong>level</strong>) is the number of times that category was observed. The <strong>relative frequency</strong> of a category is the proportion of times that category was observed; i.e., relative frequency equals frequency divided by the sample size.</p>
<p>With the <code>PlantGrowth</code> data, <code>group</code> records the treatment conditions of each plant sample. Each plant sample was treated with either a control (<code>ctrl</code>) or one of two experimental treatments (<code>trt1</code> or <code>trt2</code>). We can use the <code>table</code> function to obtain frequencies, and dividing the result by the sample size will return relative frequencies:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="chap-foundations.html#cb40-1" tabindex="-1"></a>tt <span class="ot">&lt;-</span> <span class="fu">table</span>(group)</span>
<span id="cb40-2"><a href="chap-foundations.html#cb40-2" tabindex="-1"></a>tt</span></code></pre></div>
<pre><code>## group
## ctrl trt1 trt2 
##   10   10   10</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="chap-foundations.html#cb42-1" tabindex="-1"></a>tt <span class="sc">/</span> n</span></code></pre></div>
<pre><code>## group
##      ctrl      trt1      trt2 
## 0.3333333 0.3333333 0.3333333</code></pre>
</div>
</div>
<div id="graphical-summaries" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Graphical Summaries<a href="chap-foundations.html#graphical-summaries" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have chosen to use base <code>R</code> graphics in this book in an effort to keep the level of <code>R</code> programming as simple as possible. In particular, we do not utilize the more modern <code>ggplot2</code> package.</p>
<div id="boxplot" class="section level3 hasAnchor" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Boxplot<a href="chap-foundations.html#boxplot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>boxplot</strong> is a basic visualization tool that offers a high-level summary of data, depicting quartiles, the data range, and potential outliers. The following code creates a boxplot of (the original) <code>weight</code>:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="chap-foundations.html#cb44-1" tabindex="-1"></a><span class="fu">boxplot</span>(weight)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="_main_files/figure-html/unnamed-chunk-11-1.png" alt="Boxplot of 'weight'" width="672" />
<p class="caption">
Figure 2.1: Boxplot of 'weight'
</p>
</div>
<p>The lower edge of the box equals <span class="math inline">\(Q1\)</span>, the upper edge equals <span class="math inline">\(Q3\)</span>, and the interior line segment equals the median. Thus, the box represents the inner 50% of the values. The dashed line segments extending above and below the box are referred to as "whiskers". If there are no potential outliers (according to the rule of thumb we defined above), the whiskers will extend to the minimum and maximum values. There are no potential outliers in the original <code>weight</code> variable, so the lower whisker is the minimum (3.59), and the upper whisker is the maximum (6.31).</p>
<p>To illustrate what happens when there are potential outliers, let us make the boxplot for the modified variable <code>weight_star</code>. Instead of 100, we will set the first observation to equal 10. This is still an "extreme" value, relative to the other values, but we will be better able to see the graph's features:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="chap-foundations.html#cb45-1" tabindex="-1"></a>weight_star[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb45-2"><a href="chap-foundations.html#cb45-2" tabindex="-1"></a><span class="fu">boxplot</span>(weight_star)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-12"></span>
<img src="_main_files/figure-html/unnamed-chunk-12-1.png" alt="Boxplot of `weight_star`" width="672" />
<p class="caption">
Figure 2.2: Boxplot of <code>weight_star</code>
</p>
</div>
<p>In this case, the first observation is an outlier and is therefore indicated on the graph by an individual point. The upper whisker now extends to the largest value that does not exceed <span class="math inline">\(Q3 + 1.5 \times \text{IQR}\)</span>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="chap-foundations.html#cb46-1" tabindex="-1"></a>Q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(weight_star, <span class="fl">0.25</span>)</span>
<span id="cb46-2"><a href="chap-foundations.html#cb46-2" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(weight_star, <span class="fl">0.75</span>)</span>
<span id="cb46-3"><a href="chap-foundations.html#cb46-3" tabindex="-1"></a>IQR <span class="ot">&lt;-</span> Q3 <span class="sc">-</span> Q1</span>
<span id="cb46-4"><a href="chap-foundations.html#cb46-4" tabindex="-1"></a></span>
<span id="cb46-5"><a href="chap-foundations.html#cb46-5" tabindex="-1"></a><span class="do">## We do have outliers on the upper end since the maximum value exceeds the upper </span></span>
<span id="cb46-6"><a href="chap-foundations.html#cb46-6" tabindex="-1"></a><span class="do">## rule-of-thumb bound.</span></span>
<span id="cb46-7"><a href="chap-foundations.html#cb46-7" tabindex="-1"></a><span class="fu">range</span>(weight_star)</span></code></pre></div>
<pre><code>## [1]  3.59 10.00</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="chap-foundations.html#cb48-1" tabindex="-1"></a>Q1 <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR</span></code></pre></div>
<pre><code>##  25% 
## 3.22</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="chap-foundations.html#cb50-1" tabindex="-1"></a>Q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR </span></code></pre></div>
<pre><code>##  75% 
## 6.98</code></pre>
<p>Boxplots are particularly useful for <em>comparing</em> distributions of a variable across the levels of a qualitative variable. For example, here are <strong>side-by-side boxplots</strong> of <code>weight</code>, comparing the levels of <code>group</code>:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="chap-foundations.html#cb52-1" tabindex="-1"></a><span class="fu">boxplot</span>(weight <span class="sc">~</span> group)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="_main_files/figure-html/unnamed-chunk-14-1.png" alt="Side-by-side boxplots of `weight` by `group`" width="672" />
<p class="caption">
Figure 2.3: Side-by-side boxplots of <code>weight</code> by <code>group</code>
</p>
</div>
<p>Using this graph, we can quickly see that the distribution of weights under <code>trt1</code> are shifted down relative to the <code>ctrl</code> group, and the distribution of weights under <code>trt2</code> are shifted up relative to the <code>ctrl</code> group. Note that one weight value was flagged as a potential outlier in the <code>trt1</code> group.</p>
</div>
<div id="histogram" class="section level3 hasAnchor" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> Histogram<a href="chap-foundations.html#histogram" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>histogram</strong> is another graphical summary of a distribution, providing more visual detail than a boxplot. A histogram organizes data into intervals, or bins, and illustrates the frequency or density of data points in each bin. Here is a histogram of <code>weight</code>:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="chap-foundations.html#cb53-1" tabindex="-1"></a><span class="fu">hist</span>(weight)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:PlantGrowth-weight-hist-freq"></span>
<img src="_main_files/figure-html/PlantGrowth-weight-hist-freq-1.png" alt="Histogram of 'weight'. By default, bin heights are frequencies." width="672" />
<p class="caption">
Figure 2.4: Histogram of 'weight'. By default, bin heights are frequencies.
</p>
</div>
<p>The <code>hist</code> function created six bins, each of width 0.5, across the interval from 3.5 to 6.5 and computed the frequency of <code>weight</code> values that fall within each bin. The histogram is then composed of rectangles for each bin with heights equal to the frequencies. As with a boxplot, a histogram provides a quick summary of the location and spread of a distribution.</p>
<p>While the default for the <code>hist</code> function is to display bin rectangle heights as frequencies, it is also common to define bins in terms of "density." We can specify that we want a density histogram by setting the <code>probability</code> argument equal to <code>TRUE</code>:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="chap-foundations.html#cb54-1" tabindex="-1"></a><span class="fu">hist</span>(weight, <span class="at">probability =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:PlantGrowth-weight-hist-dens"></span>
<img src="_main_files/figure-html/PlantGrowth-weight-hist-dens-1.png" alt="Histogram of 'weight', now with bin heights equal to densities." width="672" />
<p class="caption">
Figure 2.5: Histogram of 'weight', now with bin heights equal to densities.
</p>
</div>
<p>The height of a rectangle in a density histogram equals the proportion of values falling within the corresponding bin divided by the bin width. For example, as can be seen in Figure <a href="chap-foundations.html#fig:PlantGrowth-weight-hist-freq">2.4</a>, there are 2 values of <code>weight</code> that fall in the bin between 3.5 and 4.0. The height of this bin in Figure <a href="chap-foundations.html#fig:PlantGrowth-weight-hist-dens">2.5</a> is therefore <span class="math inline">\(2 / (30 * 0.5) = 0.1333\)</span>. By defining bin heights as densities, we ensure that the total of all the rectangle areas equals one. This is consistent with how we will define <strong>probability distributions</strong> in Chapters <a href="chap-probability.html#chap-probability">3</a> and <a href="chap-rvs-distributions.html#chap-rvs-distributions">4</a>. Notice that the qualitative appearance of the density histogram is the same as that of the frequency histogram; the only difference is in the definition of the bin rectangle heights.</p>
<p>There is no one right way to choose the bins for a histogram. There are many algorithms that have been developed for this purpose. One general principle is that increasing the number of bins will increase the granularity of visual detail. With too few bins, we might miss important subtle patterns to a distribution. On the other hand, with too many bins, we might be distracted by "noisy" local features in the data. In most cases, the default bin selection made by <code>hist</code> will represent a reasonable solution. Note that you can customize the bins using the <code>breaks</code> argument to <code>hist</code>.</p>
</div>
<div id="the-shape-of-a-distribution" class="section level3 hasAnchor" number="2.6.3">
<h3><span class="header-section-number">2.6.3</span> The Shape of a Distribution<a href="chap-foundations.html#the-shape-of-a-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
We now have tools for characterizing the distribution of a quantitative variable in two important ways: location (i.e., what is a "typical value") and spread (how variable are the data values). A third important characteristic of a distribution is its shape. Figure <a href="chap-foundations.html#fig:distn-shape">2.6</a> shows histograms for four simulated datasets that illustrate common distributional shapes.
<div class="figure"><span style="display:block;" id="fig:distn-shape"></span>
<img src="_main_files/figure-html/distn-shape-1.png" alt="Simulated distributions of different shapes" width="672" />
<p class="caption">
Figure 2.6: Simulated distributions of different shapes
</p>
</div>
<p>Beginning in row one and going left to right, the first distribution is <strong>symmetric</strong>, the second is <strong>multimodal</strong> (specifically, <strong>bimodal</strong>) in the sense that it has more than one peak or "modes", the third is <strong>right skewed</strong>, and the fourth is <strong>left skewed</strong>.</p>
<p>We can additionally diagnose skew by comparing the mean and the median. The median, being more robust, won't be 'pulled' as dramatically (or even sometimes at all) by the tail. By comparison, the mean always will be affected. Hence, if the mean is approximately equal to the median, that gives us information that the distribution is at least close to symmetric. If the median is much greater than the mean, the the distribution is skewed to the left. If the median is much less than the mean then the distribution is skewed to the right.</p>

</div>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  },
  "info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
