<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Hypothesis Testing | Probability and Statistics: Making Principled Decisions in an Uncertain World</title>
  <meta name="description" content="OER textbook designed to support calculus-based introductory undergraduate statistics training. At Texas A&amp;M University, this book is appropriate for the two-course sequence STAT 211 &amp; 212." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Hypothesis Testing | Probability and Statistics: Making Principled Decisions in an Uncertain World" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="OER textbook designed to support calculus-based introductory undergraduate statistics training. At Texas A&amp;M University, this book is appropriate for the two-course sequence STAT 211 &amp; 212." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Hypothesis Testing | Probability and Statistics: Making Principled Decisions in an Uncertain World" />
  
  <meta name="twitter:description" content="OER textbook designed to support calculus-based introductory undergraduate statistics training. At Texas A&amp;M University, this book is appropriate for the two-course sequence STAT 211 &amp; 212." />
  

<meta name="author" content="Alan Dabney, Scott Crawford, Darren Homrighausen" />


<meta name="date" content="2026-08-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-confidence-intervals.html"/>
<link rel="next" href="chap-compare-two.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.25.2/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about"><i class="fa fa-check"></i><b>1.1</b> About</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.2</b> R</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#supplemental-resources"><i class="fa fa-check"></i><b>1.3</b> Supplemental Resources</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.4</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-foundations.html"><a href="chap-foundations.html"><i class="fa fa-check"></i><b>2</b> Foundations</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-foundations.html"><a href="chap-foundations.html#what-is-statistics"><i class="fa fa-check"></i><b>2.1</b> What is Statistics?</a></li>
<li class="chapter" data-level="2.2" data-path="chap-foundations.html"><a href="chap-foundations.html#populations-and-parameters-samples-and-statistics"><i class="fa fa-check"></i><b>2.2</b> Populations and Parameters, Samples and Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="chap-foundations.html"><a href="chap-foundations.html#obtaining-data"><i class="fa fa-check"></i><b>2.3</b> Obtaining Data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chap-foundations.html"><a href="chap-foundations.html#chap-foundations-sampling"><i class="fa fa-check"></i><b>2.3.1</b> Sampling</a></li>
<li class="chapter" data-level="2.3.2" data-path="chap-foundations.html"><a href="chap-foundations.html#chap-foundations-observational-experiment"><i class="fa fa-check"></i><b>2.3.2</b> <span id="def-foundations-observational-studies">Observational Studies</span> and Experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-foundations.html"><a href="chap-foundations.html#sec-foundations-nature-of-data"><i class="fa fa-check"></i><b>2.4</b> The Nature of Data</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chap-foundations.html"><a href="chap-foundations.html#randomness-and-uncertainty"><i class="fa fa-check"></i><b>2.4.1</b> Randomness and Uncertainty</a></li>
<li class="chapter" data-level="2.4.2" data-path="chap-foundations.html"><a href="chap-foundations.html#random-variables"><i class="fa fa-check"></i><b>2.4.2</b> Random Variables</a></li>
<li class="chapter" data-level="2.4.3" data-path="chap-foundations.html"><a href="chap-foundations.html#notation"><i class="fa fa-check"></i><b>2.4.3</b> Notation</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chap-foundations.html"><a href="chap-foundations.html#numerical-summaries"><i class="fa fa-check"></i><b>2.5</b> Summary Statistics</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="chap-foundations.html"><a href="chap-foundations.html#mean"><i class="fa fa-check"></i><b>2.5.1</b> Mean</a></li>
<li class="chapter" data-level="2.5.2" data-path="chap-foundations.html"><a href="chap-foundations.html#sec-percentiles-median"><i class="fa fa-check"></i><b>2.5.2</b> Percentiles and Median</a></li>
<li class="chapter" data-level="2.5.3" data-path="chap-foundations.html"><a href="chap-foundations.html#variance-and-standard-deviation"><i class="fa fa-check"></i><b>2.5.3</b> Variance and Standard Deviation</a></li>
<li class="chapter" data-level="2.5.4" data-path="chap-foundations.html"><a href="chap-foundations.html#extreme-values-and-robust-statistics"><i class="fa fa-check"></i><b>2.5.4</b> Extreme Values and Robust Statistics</a></li>
<li class="chapter" data-level="2.5.5" data-path="chap-foundations.html"><a href="chap-foundations.html#frequency-and-relative-frequency"><i class="fa fa-check"></i><b>2.5.5</b> <span id="def-foundations-frequency">Frequency</span> and <span id="def-foundations-relative-frequency">Relative Frequency</span></a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chap-foundations.html"><a href="chap-foundations.html#graphical-summaries"><i class="fa fa-check"></i><b>2.6</b> Graphical Summaries</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="chap-foundations.html"><a href="chap-foundations.html#boxplot"><i class="fa fa-check"></i><b>2.6.1</b> <span id="def-foundations-boxplot">Boxplot</span></a></li>
<li class="chapter" data-level="2.6.2" data-path="chap-foundations.html"><a href="chap-foundations.html#histogram"><i class="fa fa-check"></i><b>2.6.2</b> <span id="def-foundations-histogram">Histogram</span></a></li>
<li class="chapter" data-level="2.6.3" data-path="chap-foundations.html"><a href="chap-foundations.html#the-shape-of-a-distribution"><i class="fa fa-check"></i><b>2.6.3</b> The Shape of a Distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-probability.html"><a href="chap-probability.html"><i class="fa fa-check"></i><b>3</b> <span id="def-probability-probability">Probability</span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-probability.html"><a href="chap-probability.html#motivation-and-intuition"><i class="fa fa-check"></i><b>3.1</b> Motivation and Intuition</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="chap-probability.html"><a href="chap-probability.html#previewing-statistical-inference"><i class="fa fa-check"></i><b>3.1.1</b> Previewing Statistical Inference</a></li>
<li class="chapter" data-level="3.1.2" data-path="chap-probability.html"><a href="chap-probability.html#probability-a-long-run-average"><i class="fa fa-check"></i><b>3.1.2</b> Probability: A "Long-Run Average"</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chap-probability.html"><a href="chap-probability.html#sample-spaces-and-events"><i class="fa fa-check"></i><b>3.2</b> Sample Spaces and Events</a></li>
<li class="chapter" data-level="3.3" data-path="chap-probability.html"><a href="chap-probability.html#axioms-and-properties"><i class="fa fa-check"></i><b>3.3</b> Axioms and Properties</a></li>
<li class="chapter" data-level="3.4" data-path="chap-probability.html"><a href="chap-probability.html#sec-probability-counting"><i class="fa fa-check"></i><b>3.4</b> Counting</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="chap-probability.html"><a href="chap-probability.html#product-rule"><i class="fa fa-check"></i><b>3.4.1</b> Product Rule</a></li>
<li class="chapter" data-level="3.4.2" data-path="chap-probability.html"><a href="chap-probability.html#permutations-and-combinations"><i class="fa fa-check"></i><b>3.4.2</b> Permutations and Combinations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chap-probability.html"><a href="chap-probability.html#conditional-probability"><i class="fa fa-check"></i><b>3.5</b> <span id="def-probability-conditional-probability">Conditional Probability</span></a></li>
<li class="chapter" data-level="3.6" data-path="chap-probability.html"><a href="chap-probability.html#independence"><i class="fa fa-check"></i><b>3.6</b> Independence</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html"><i class="fa fa-check"></i><b>4</b> Random Variables and Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#random-variables-1"><i class="fa fa-check"></i><b>4.1</b> Random Variables</a></li>
<li class="chapter" data-level="4.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#probability-functions"><i class="fa fa-check"></i><b>4.2</b> Probability Functions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#probability-mass-function-discrete-rvs"><i class="fa fa-check"></i><b>4.2.1</b> Probability Mass Function (Discrete RVs)</a></li>
<li class="chapter" data-level="4.2.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#chap-rvs-sec-pdf"><i class="fa fa-check"></i><b>4.2.2</b> Probability Density Function (Continuous RVs)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#chap-rvs-sec-cdf"><i class="fa fa-check"></i><b>4.3</b> <span id="def-random-variables-and-probability-distributions-cumulative-distribution-function">Cumulative Distribution Function</span></a></li>
<li class="chapter" data-level="4.4" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#discrete-distributions"><i class="fa fa-check"></i><b>4.4</b> Discrete Distributions</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#binomial-distribution"><i class="fa fa-check"></i><b>4.4.1</b> <span id="def-random-variables-and-probability-distributions-binomial-n-p">Binomial</span> Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#distributions-related-to-the-bernoulli"><i class="fa fa-check"></i><b>4.4.2</b> Distributions Related to the Bernoulli</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#continuous-distributions"><i class="fa fa-check"></i><b>4.5</b> Continuous Distributions</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#sec-exponential"><i class="fa fa-check"></i><b>4.5.1</b> <span id="def-random-variables-and-probability-distributions-exponential">Exponential</span> Distribution</a></li>
<li class="chapter" data-level="4.5.2" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#gamma-distribution"><i class="fa fa-check"></i><b>4.5.2</b> <span id="def-random-variables-and-probability-distributions-gamma">Gamma</span> Distribution</a></li>
<li class="chapter" data-level="4.5.3" data-path="chap-rvs-distributions.html"><a href="chap-rvs-distributions.html#sec-chi-squared-distribution"><i class="fa fa-check"></i><b>4.5.3</b> Chi-Squared Distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-expected-value.html"><a href="chap-expected-value.html"><i class="fa fa-check"></i><b>5</b> <span id="def-expected-value-expected-value">Expected Value</span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-expected-value.html"><a href="chap-expected-value.html#expected-value-for-discrete-variables"><i class="fa fa-check"></i><b>5.1</b> Expected Value for Discrete Variables</a></li>
<li class="chapter" data-level="5.2" data-path="chap-expected-value.html"><a href="chap-expected-value.html#expected-value-for-continuous-variables"><i class="fa fa-check"></i><b>5.2</b> Expected Value for Continuous Variables</a></li>
<li class="chapter" data-level="5.3" data-path="chap-expected-value.html"><a href="chap-expected-value.html#expected-value-for-linear-functions"><i class="fa fa-check"></i><b>5.3</b> Expected Value for Linear Functions</a></li>
<li class="chapter" data-level="5.4" data-path="chap-expected-value.html"><a href="chap-expected-value.html#variance-and-standard-deviation-1"><i class="fa fa-check"></i><b>5.4</b> <span id="def-expected-value-variance">Variance</span> and <span id="def-expected-value-standard-deviation">Standard Deviation</span></a></li>
<li class="chapter" data-level="5.5" data-path="chap-expected-value.html"><a href="chap-expected-value.html#means-and-variances-of-common-distributions"><i class="fa fa-check"></i><b>5.5</b> Means and Variances of Common Distributions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="chap-expected-value.html"><a href="chap-expected-value.html#binomial"><i class="fa fa-check"></i><b>5.5.1</b> <span id="def-expected-value-binomial">Binomial</span></a></li>
<li class="chapter" data-level="5.5.2" data-path="chap-expected-value.html"><a href="chap-expected-value.html#hypergeometric"><i class="fa fa-check"></i><b>5.5.2</b> <span id="def-expected-value-hypergeometric">Hypergeometric</span></a></li>
<li class="chapter" data-level="5.5.3" data-path="chap-expected-value.html"><a href="chap-expected-value.html#negative-binomial"><i class="fa fa-check"></i><b>5.5.3</b> <span id="def-expected-value-negative-binomial">Negative Binomial</span></a></li>
<li class="chapter" data-level="5.5.4" data-path="chap-expected-value.html"><a href="chap-expected-value.html#poisson"><i class="fa fa-check"></i><b>5.5.4</b> <span id="def-expected-value-poisson">Poisson</span></a></li>
<li class="chapter" data-level="5.5.5" data-path="chap-expected-value.html"><a href="chap-expected-value.html#exponential"><i class="fa fa-check"></i><b>5.5.5</b> <span id="def-expected-value-exponential">Exponential</span></a></li>
<li class="chapter" data-level="5.5.6" data-path="chap-expected-value.html"><a href="chap-expected-value.html#gamma"><i class="fa fa-check"></i><b>5.5.6</b> <span id="def-expected-value-gamma">Gamma</span></a></li>
<li class="chapter" data-level="5.5.7" data-path="chap-expected-value.html"><a href="chap-expected-value.html#chi-squared"><i class="fa fa-check"></i><b>5.5.7</b> Chi-Squared</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="chap-expected-value.html"><a href="chap-expected-value.html#moment-generating-functions"><i class="fa fa-check"></i><b>5.6</b> <span id="def-expected-value-the-moment">Moment</span> Generating Functions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html"><i class="fa fa-check"></i><b>6</b> The <span id="def-the-normal-distribution-normal-distribution">Normal Distribution</span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#the-normal-and-standard-normal-distributions"><i class="fa fa-check"></i><b>6.1</b> The Normal and Standard Normal Distributions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#chap-non-standard-normal"><i class="fa fa-check"></i><b>6.1.1</b> The Normal Distribution</a></li>
<li class="chapter" data-level="6.1.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#chap-standard-normal"><i class="fa fa-check"></i><b>6.1.2</b> The <span id="def-the-normal-distribution-standard-normal-distribution">Standard Normal Distribution</span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#standardization"><i class="fa fa-check"></i><b>6.2</b> <span id="def-the-normal-distribution-standardization">Standardization</span></a></li>
<li class="chapter" data-level="6.3" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#z-scores"><i class="fa fa-check"></i><b>6.3</b> <span class="math inline">\(z\)</span>-scores</a></li>
<li class="chapter" data-level="6.4" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#probabilities"><i class="fa fa-check"></i><b>6.4</b> Probabilities</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#computing-standard-normal-probabilities"><i class="fa fa-check"></i><b>6.4.1</b> Computing Standard Normal Probabilities</a></li>
<li class="chapter" data-level="6.4.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#computing-normal-probabilities"><i class="fa fa-check"></i><b>6.4.2</b> Computing Normal Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#quantiles"><i class="fa fa-check"></i><b>6.5</b> Quantiles</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#sec-normal-percentiles-visual"><i class="fa fa-check"></i><b>6.5.1</b> Computing Standard Normal Quantiles</a></li>
<li class="chapter" data-level="6.5.2" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#chap-normal-percentiles"><i class="fa fa-check"></i><b>6.5.2</b> Computing Normal Quantiles</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#sec-QQ-plots"><i class="fa fa-check"></i><b>6.6</b> Q-Q Plots for Checking Normality</a></li>
<li class="chapter" data-level="6.7" data-path="chap-normal-distribution.html"><a href="chap-normal-distribution.html#sec-t-distribution"><i class="fa fa-check"></i><b>6.7</b> t Distribution</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html"><i class="fa fa-check"></i><b>7</b> Joint and Conditional Distributions</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#jointly-distributed-random-variables"><i class="fa fa-check"></i><b>7.1</b> Jointly Distributed Random Variables</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#discrete-random-variables"><i class="fa fa-check"></i><b>7.1.1</b> Discrete Random Variables</a></li>
<li class="chapter" data-level="7.1.2" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#continuous-random-variables"><i class="fa fa-check"></i><b>7.1.2</b> Continuous Random Variables</a></li>
<li class="chapter" data-level="7.1.3" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#more-than-two-random-variables"><i class="fa fa-check"></i><b>7.1.3</b> More Than Two Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#independence-1"><i class="fa fa-check"></i><b>7.2</b> Independence</a></li>
<li class="chapter" data-level="7.3" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#conditional-probability-functions"><i class="fa fa-check"></i><b>7.3</b> <span id="def-joint-and-conditional-distributions-conditional-probability-function">Conditional Probability Functions</span></a></li>
<li class="chapter" data-level="7.4" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#sec-conditional-expectation"><i class="fa fa-check"></i><b>7.4</b> Conditional Expected Values</a></li>
<li class="chapter" data-level="7.5" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#sec-cov-and-corr"><i class="fa fa-check"></i><b>7.5</b> Covariance and Correlation</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#covariance"><i class="fa fa-check"></i><b>7.5.1</b> Covariance</a></li>
<li class="chapter" data-level="7.5.2" data-path="chap-joint-conditional.html"><a href="chap-joint-conditional.html#correlation"><i class="fa fa-check"></i><b>7.5.2</b> Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html"><i class="fa fa-check"></i><b>8</b> Sampling Distributions and <span id="def-sampling-distributions-and-central-limit-theorem-central-limit-theorem-clt">Central Limit Theorem</span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#what-is-a-sampling-distribution-and-why-should-you-care"><i class="fa fa-check"></i><b>8.1</b> What Is a <span id="def-sampling-distributions-and-central-limit-theorem-sampling-distribution">Sampling Distribution</span>, and Why Should You Care?</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#preliminary-definitions"><i class="fa fa-check"></i><b>8.1.1</b> Preliminary Definitions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#illustration-via-simulation"><i class="fa fa-check"></i><b>8.2</b> Illustration Via Simulation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#chap-sampling-distributions-sim-normal"><i class="fa fa-check"></i><b>8.2.1</b> Simulation Setup: Normal Population</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sec-distn-sample-mean"><i class="fa fa-check"></i><b>8.3</b> The Distribution of the Sample Mean</a></li>
<li class="chapter" data-level="8.4" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>8.4</b> The Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#simulation-setup-non-normal-population"><i class="fa fa-check"></i><b>8.4.1</b> Simulation Setup: Non-Normal Population</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html"><i class="fa fa-check"></i><b>9</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#introduction"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#motivation-and-pivots-sec-ci-pivot-method"><i class="fa fa-check"></i><b>9.2</b> Motivation and Pivots {#sec-CI-<span id="def-confidence-intervals-pivot">pivot</span>-method}</a></li>
<li class="chapter" data-level="9.3" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-mean"><i class="fa fa-check"></i><b>9.3</b> Confidence Interval for the Population Mean <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-samp-dist-normal"><i class="fa fa-check"></i><b>9.3.1</b> Sampling Distribution conditions</a></li>
<li class="chapter" data-level="9.3.2" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-mean-known-sigma"><i class="fa fa-check"></i><b>9.3.2</b> When <span class="math inline">\(\sigma\)</span> is known (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="9.3.3" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-mean-unknown-sigma"><i class="fa fa-check"></i><b>9.3.3</b> When <span class="math inline">\(\sigma\)</span> is unknown (Using the t Distribution)</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-matchedPairs"><i class="fa fa-check"></i><b>9.4</b> Confidence Interval for Matched Pairs</a></li>
<li class="chapter" data-level="9.5" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-proportion"><i class="fa fa-check"></i><b>9.5</b> Confidence Interval for a Population Proportion (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="9.6" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-CI-variance"><i class="fa fa-check"></i><b>9.6</b> Confidence Interval for a Population Variance (Using the <span class="math inline">\(\chi^2\)</span> Distribution)</a></li>
<li class="chapter" data-level="9.7" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-ci-interpret"><i class="fa fa-check"></i><b>9.7</b> Interpreting a Confidence Interval</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#chap-confidence-intervals-simulation"><i class="fa fa-check"></i><b>9.7.1</b> A Deeper Look at the Idea of Confidence</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#finding-the-sample-size-n-for-a-particular-confidence-interval-sec-precision-sample-size"><i class="fa fa-check"></i><b>9.8</b> Finding the Sample Size (<span class="math inline">\(n\)</span>) for a Particular Confidence Interval {#sec-<span id="def-confidence-intervals-precision">precision</span>-sample-size}</a></li>
<li class="chapter" data-level="9.9" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#other-types-of-intervals"><i class="fa fa-check"></i><b>9.9</b> Other Types of Intervals</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#sec-ci-prediction"><i class="fa fa-check"></i><b>9.9.1</b> Prediction Intervals</a></li>
<li class="chapter" data-level="9.9.2" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#tolerance-intervals"><i class="fa fa-check"></i><b>9.9.2</b> Tolerance Intervals</a></li>
<li class="chapter" data-level="9.9.3" data-path="chap-confidence-intervals.html"><a href="chap-confidence-intervals.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>9.9.3</b> Bootstrap Confidence Intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html"><i class="fa fa-check"></i><b>10</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#logic-and-language-of-hypothesis-testing"><i class="fa fa-check"></i><b>10.1</b> Logic and Language of Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#chap-ht-definitions"><i class="fa fa-check"></i><b>10.1.1</b> <span id="def-hypothesis-testing-type-i-error-type-1-error">Type I Error</span>, <span id="def-hypothesis-testing-type-ii-error-type-2-error">Type II error</span>, and <span id="def-hypothesis-testing-power">Power</span></a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-test-mean"><i class="fa fa-check"></i><b>10.2</b> Hypothesis Test for a Population Mean</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-mean-known-sigma"><i class="fa fa-check"></i><b>10.2.1</b> When <span class="math inline">\(\sigma\)</span> is known (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="10.2.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-mean-unknown-sigma"><i class="fa fa-check"></i><b>10.2.2</b> When <span class="math inline">\(\sigma\)</span> is unknown (Using the t Distribution)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#hypothesis-test-for-matched-pairs"><i class="fa fa-check"></i><b>10.3</b> Hypothesis Test for Matched Pairs</a></li>
<li class="chapter" data-level="10.4" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-proportion"><i class="fa fa-check"></i><b>10.4</b> Hypothesis Test for a Population Proportion</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#hypothesis-test-for-a-population-variance"><i class="fa fa-check"></i><b>10.4.1</b> Hypothesis Test for a Population Variance</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-one-vs-two"><i class="fa fa-check"></i><b>10.5</b> Two-sided and One-sided Tests</a></li>
<li class="chapter" data-level="10.6" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#sec-HT-power"><i class="fa fa-check"></i><b>10.6</b> Power</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations-for-mu"><i class="fa fa-check"></i><b>10.6.1</b> Power and Sample Size Calculations for <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="10.6.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations"><i class="fa fa-check"></i><b>10.6.2</b> Power and Sample Size Calculations</a></li>
<li class="chapter" data-level="10.6.3" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations-for-chi2"><i class="fa fa-check"></i><b>10.6.3</b> Power and Sample Size Calculations for <span class="math inline">\(\chi^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#exploring-hypothesis-test-via-simulation"><i class="fa fa-check"></i><b>10.7</b> Exploring Hypothesis Test via simulation</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#the-test-statistic-and-its-sampling-distribution-assuming-h_0-is-true"><i class="fa fa-check"></i><b>10.7.1</b> The Test Statistic and its Sampling Distribution: Assuming <span class="math inline">\(H_0\)</span> is true</a></li>
<li class="chapter" data-level="10.7.2" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#simulation-study-repeated-hypothesis-testing-under-h_0-and-h_a"><i class="fa fa-check"></i><b>10.7.2</b> Simulation Study: Repeated Hypothesis Testing Under <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span></a></li>
<li class="chapter" data-level="10.7.3" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#bootstrap-hypothesis-tests"><i class="fa fa-check"></i><b>10.7.3</b> Bootstrap Hypothesis Tests</a></li>
<li class="chapter" data-level="10.7.4" data-path="chap-hypothesis-testing.html"><a href="chap-hypothesis-testing.html#the-basic-bootstrap-hypothesis-test-procedure"><i class="fa fa-check"></i><b>10.7.4</b> The Basic Bootstrap Hypothesis Test Procedure</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chap-compare-two.html"><a href="chap-compare-two.html"><i class="fa fa-check"></i><b>11</b> Comparing Two Populations</a>
<ul>
<li class="chapter" data-level="11.1" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-two-sample-means"><i class="fa fa-check"></i><b>11.1</b> Inference on a Difference of Two Population Means</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="chap-compare-two.html"><a href="chap-compare-two.html#when-sds-are-known-using-the-normal-distribution"><i class="fa fa-check"></i><b>11.1.1</b> When SDs are Known (Using the Normal Distribution)</a></li>
<li class="chapter" data-level="11.1.2" data-path="chap-compare-two.html"><a href="chap-compare-two.html#when-sds-are-unknown-using-the-t-distribution"><i class="fa fa-check"></i><b>11.1.2</b> When SDs are Unknown (Using the T Distribution)</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-2pop-proportion"><i class="fa fa-check"></i><b>11.2</b> Difference of Two Population Proportions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-2pop-CI-proportion"><i class="fa fa-check"></i><b>11.2.1</b> Confidence Intervals for Two Population Proportions</a></li>
<li class="chapter" data-level="11.2.2" data-path="chap-compare-two.html"><a href="chap-compare-two.html#sec-2pop-HT-proportion"><i class="fa fa-check"></i><b>11.2.2</b> Hypothesis Tests for Two Population Proportions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="chap-compare-two.html"><a href="chap-compare-two.html#inference-on-a-ratio-of-two-population-variances"><i class="fa fa-check"></i><b>11.3</b> Inference on a Ratio of Two Population Variances</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="chap-compare-more-than-two.html"><a href="chap-compare-more-than-two.html"><i class="fa fa-check"></i><b>12</b> Comparing More Than Two Populations</a></li>
<li class="chapter" data-level="13" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html"><i class="fa fa-check"></i><b>13</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="13.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-model"><i class="fa fa-check"></i><b>13.1</b> The Simple Linear Regression (SLR) Model</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-regression"><i class="fa fa-check"></i><b>13.1.1</b> What Does the Word Regression Mean?</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-least-squares"><i class="fa fa-check"></i><b>13.2</b> The Least Squares Idea</a></li>
<li class="chapter" data-level="13.3" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-assumptions"><i class="fa fa-check"></i><b>13.3</b> Checking the Assumptions</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#good-residuals"><i class="fa fa-check"></i><b>13.3.1</b> Good Residuals</a></li>
<li class="chapter" data-level="13.3.2" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#linearity"><i class="fa fa-check"></i><b>13.3.2</b> Linearity</a></li>
<li class="chapter" data-level="13.3.3" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#constant-variance"><i class="fa fa-check"></i><b>13.3.3</b> Constant Variance</a></li>
<li class="chapter" data-level="13.3.4" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#independence-2"><i class="fa fa-check"></i><b>13.3.4</b> Independence</a></li>
<li class="chapter" data-level="13.3.5" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#normality"><i class="fa fa-check"></i><b>13.3.5</b> Normality</a></li>
<li class="chapter" data-level="13.3.6" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#multiple-assumptions-being-violated"><i class="fa fa-check"></i><b>13.3.6</b> Multiple Assumptions being Violated</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-covariance-correlation"><i class="fa fa-check"></i><b>13.4</b> Covariance, Correlation, and R-squared</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#r-squared"><i class="fa fa-check"></i><b>13.4.1</b> R-squared</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-ci"><i class="fa fa-check"></i><b>13.5</b> Confidence Intervals</a></li>
<li class="chapter" data-level="13.6" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-pi"><i class="fa fa-check"></i><b>13.6</b> Prediction Intervals</a></li>
<li class="chapter" data-level="13.7" data-path="chap-simple-linear-regression.html"><a href="chap-simple-linear-regression.html#sec-slr-ht"><i class="fa fa-check"></i><b>13.7</b> Hypothesis Test</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chap-multiple-linear-regression.html"><a href="chap-multiple-linear-regression.html"><i class="fa fa-check"></i><b>14</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="15" data-path="chap-flexible-regression.html"><a href="chap-flexible-regression.html"><i class="fa fa-check"></i><b>15</b> More Flexible Regression Methods</a></li>
<li class="chapter" data-level="16" data-path="chap-categorical-data.html"><a href="chap-categorical-data.html"><i class="fa fa-check"></i><b>16</b> Categorical Data Analysis</a></li>
<li class="chapter" data-level="17" data-path="chap-nonparametrics.html"><a href="chap-nonparametrics.html"><i class="fa fa-check"></i><b>17</b> Nonparametric Methods</a></li>
<li class="chapter" data-level="18" data-path="chap-exercises.html"><a href="chap-exercises.html"><i class="fa fa-check"></i><b>18</b> Exercises</a>
<ul>
<li class="chapter" data-level="18.1" data-path="chap-exercises.html"><a href="chap-exercises.html#foundations"><i class="fa fa-check"></i><b>18.1</b> Foundations</a></li>
<li class="chapter" data-level="18.2" data-path="chap-exercises.html"><a href="chap-exercises.html#probability"><i class="fa fa-check"></i><b>18.2</b> Probability</a></li>
<li class="chapter" data-level="18.3" data-path="chap-exercises.html"><a href="chap-exercises.html#expected-values"><i class="fa fa-check"></i><b>18.3</b> Expected Values</a></li>
<li class="chapter" data-level="18.4" data-path="chap-exercises.html"><a href="chap-exercises.html#joint-and-conditional-probability"><i class="fa fa-check"></i><b>18.4</b> Joint and Conditional Probability</a></li>
<li class="chapter" data-level="18.5" data-path="chap-exercises.html"><a href="chap-exercises.html#sampling-distributions"><i class="fa fa-check"></i><b>18.5</b> Sampling Distributions</a></li>
<li class="chapter" data-level="18.6" data-path="chap-exercises.html"><a href="chap-exercises.html#principles-of-statistical-inference"><i class="fa fa-check"></i><b>18.6</b> Principles of Statistical Inference</a></li>
<li class="chapter" data-level="18.7" data-path="chap-exercises.html"><a href="chap-exercises.html#confidence-intervals"><i class="fa fa-check"></i><b>18.7</b> Confidence Intervals</a></li>
<li class="chapter" data-level="18.8" data-path="chap-exercises.html"><a href="chap-exercises.html#hypothesis-testing"><i class="fa fa-check"></i><b>18.8</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="18.9" data-path="chap-exercises.html"><a href="chap-exercises.html#comparing-two-populations"><i class="fa fa-check"></i><b>18.9</b> Comparing Two Populations</a></li>
<li class="chapter" data-level="18.10" data-path="chap-exercises.html"><a href="chap-exercises.html#comparing-more-than-two-populations"><i class="fa fa-check"></i><b>18.10</b> Comparing More Than Two Populations</a></li>
<li class="chapter" data-level="18.11" data-path="chap-exercises.html"><a href="chap-exercises.html#linear-regression"><i class="fa fa-check"></i><b>18.11</b> Linear Regression</a></li>
<li class="chapter" data-level="18.12" data-path="chap-exercises.html"><a href="chap-exercises.html#more-flexible-regression-methods"><i class="fa fa-check"></i><b>18.12</b> More Flexible Regression Methods</a></li>
<li class="chapter" data-level="18.13" data-path="chap-exercises.html"><a href="chap-exercises.html#categorical-data-analysis"><i class="fa fa-check"></i><b>18.13</b> Categorical Data Analysis</a></li>
<li class="chapter" data-level="18.14" data-path="chap-exercises.html"><a href="chap-exercises.html#nonparametric-methods"><i class="fa fa-check"></i><b>18.14</b> Nonparametric Methods</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html"><i class="fa fa-check"></i><b>19</b> Appendix: R Tutorial</a>
<ul>
<li class="chapter" data-level="19.1" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#downloading-and-installing-r-and-rstudio"><i class="fa fa-check"></i><b>19.1</b> Downloading and Installing R and RStudio</a></li>
<li class="chapter" data-level="19.2" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-layout-of-rstudio"><i class="fa fa-check"></i><b>19.2</b> The Layout of RStudio</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-source-pane"><i class="fa fa-check"></i><b>19.2.1</b> The Source Pane</a></li>
<li class="chapter" data-level="19.2.2" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-console-pane"><i class="fa fa-check"></i><b>19.2.2</b> The Console Pane</a></li>
<li class="chapter" data-level="19.2.3" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-environments-pane"><i class="fa fa-check"></i><b>19.2.3</b> The Environments Pane</a></li>
<li class="chapter" data-level="19.2.4" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#the-output-pane"><i class="fa fa-check"></i><b>19.2.4</b> The Output Pane</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#r-basics"><i class="fa fa-check"></i><b>19.3</b> R Basics</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#creating-a-.r-file"><i class="fa fa-check"></i><b>19.3.1</b> Creating a .R file</a></li>
<li class="chapter" data-level="19.3.2" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#saving-your-.r-file"><i class="fa fa-check"></i><b>19.3.2</b> Saving your .R file</a></li>
<li class="chapter" data-level="19.3.3" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#importing-data-into-r-for-analysis"><i class="fa fa-check"></i><b>19.3.3</b> Importing Data into R for Analysis</a></li>
<li class="chapter" data-level="19.3.4" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#coding-in-rstudio"><i class="fa fa-check"></i><b>19.3.4</b> Coding in RStudio</a></li>
<li class="chapter" data-level="19.3.5" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#comments"><i class="fa fa-check"></i><b>19.3.5</b> Comments</a></li>
<li class="chapter" data-level="19.3.6" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#arithmetic-in-r"><i class="fa fa-check"></i><b>19.3.6</b> Arithmetic in R</a></li>
<li class="chapter" data-level="19.3.7" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#variables-and-variable-assignment"><i class="fa fa-check"></i><b>19.3.7</b> Variables and Variable Assignment</a></li>
<li class="chapter" data-level="19.3.8" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#data-types-in-r"><i class="fa fa-check"></i><b>19.3.8</b> Data Types in R</a></li>
<li class="chapter" data-level="19.3.9" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#vectors"><i class="fa fa-check"></i><b>19.3.9</b> Vectors</a></li>
<li class="chapter" data-level="19.3.10" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#logical-operators-in-r"><i class="fa fa-check"></i><b>19.3.10</b> Logical Operators in R</a></li>
<li class="chapter" data-level="19.3.11" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#matrices-in-r"><i class="fa fa-check"></i><b>19.3.11</b> Matrices in R</a></li>
<li class="chapter" data-level="19.3.12" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#factors-in-r"><i class="fa fa-check"></i><b>19.3.12</b> Factors in R</a></li>
<li class="chapter" data-level="19.3.13" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#data-frames-in-r"><i class="fa fa-check"></i><b>19.3.13</b> Data Frames in R</a></li>
<li class="chapter" data-level="19.3.14" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#lists-in-r"><i class="fa fa-check"></i><b>19.3.14</b> Lists in R</a></li>
<li class="chapter" data-level="19.3.15" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#statistics-in-r"><i class="fa fa-check"></i><b>19.3.15</b> Statistics in R</a></li>
<li class="chapter" data-level="19.3.16" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#visualizations-in-r"><i class="fa fa-check"></i><b>19.3.16</b> Visualizations in R</a></li>
<li class="chapter" data-level="19.3.17" data-path="chap-r-tutorial.html"><a href="chap-r-tutorial.html#downloading-and-using-packages-in-r"><i class="fa fa-check"></i><b>19.3.17</b> Downloading and Using Packages in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="chap-glossary.html"><a href="chap-glossary.html"><i class="fa fa-check"></i><b>20</b> Glossary</a>
<ul>
<li class="chapter" data-level="20.1" data-path="chap-glossary.html"><a href="chap-glossary.html#overview"><i class="fa fa-check"></i><b>20.1</b> Overview</a></li>
<li class="chapter" data-level="20.2" data-path="chap-glossary.html"><a href="chap-glossary.html#foundations-1"><i class="fa fa-check"></i><b>20.2</b> Foundations</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions"><i class="fa fa-check"></i><b>20.2.1</b> Definitions</a></li>
<li class="chapter" data-level="20.2.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands"><i class="fa fa-check"></i><b>20.2.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="chap-glossary.html"><a href="chap-glossary.html#probability-1"><i class="fa fa-check"></i><b>20.3</b> Probability</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-1"><i class="fa fa-check"></i><b>20.3.1</b> Definitions</a></li>
<li class="chapter" data-level="20.3.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-1"><i class="fa fa-check"></i><b>20.3.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="chap-glossary.html"><a href="chap-glossary.html#random-variables-and-probability-distributions-1"><i class="fa fa-check"></i><b>20.4</b> Random Variables and Probability Distributions</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-2"><i class="fa fa-check"></i><b>20.4.1</b> Definitions</a></li>
<li class="chapter" data-level="20.4.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-2"><i class="fa fa-check"></i><b>20.4.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="chap-glossary.html"><a href="chap-glossary.html#expected-value"><i class="fa fa-check"></i><b>20.5</b> Expected Value</a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-3"><i class="fa fa-check"></i><b>20.5.1</b> Definitions</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="chap-glossary.html"><a href="chap-glossary.html#the-normal-distribution"><i class="fa fa-check"></i><b>20.6</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-4"><i class="fa fa-check"></i><b>20.6.1</b> Definitions</a></li>
<li class="chapter" data-level="20.6.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-3"><i class="fa fa-check"></i><b>20.6.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.7" data-path="chap-glossary.html"><a href="chap-glossary.html#joint-and-conditional-distributions"><i class="fa fa-check"></i><b>20.7</b> Joint and Conditional Distributions</a>
<ul>
<li class="chapter" data-level="20.7.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-5"><i class="fa fa-check"></i><b>20.7.1</b> Definitions</a></li>
</ul></li>
<li class="chapter" data-level="20.8" data-path="chap-glossary.html"><a href="chap-glossary.html#sampling-distributions-and-central-limit-theorem"><i class="fa fa-check"></i><b>20.8</b> Sampling Distributions and Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="20.8.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-6"><i class="fa fa-check"></i><b>20.8.1</b> Definitions</a></li>
<li class="chapter" data-level="20.8.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-4"><i class="fa fa-check"></i><b>20.8.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.9" data-path="chap-glossary.html"><a href="chap-glossary.html#confidence-intervals-1"><i class="fa fa-check"></i><b>20.9</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="20.9.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-7"><i class="fa fa-check"></i><b>20.9.1</b> Definitions</a></li>
<li class="chapter" data-level="20.9.2" data-path="chap-glossary.html"><a href="chap-glossary.html#r-commands-5"><i class="fa fa-check"></i><b>20.9.2</b> R Commands</a></li>
</ul></li>
<li class="chapter" data-level="20.10" data-path="chap-glossary.html"><a href="chap-glossary.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>20.10</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="20.10.1" data-path="chap-glossary.html"><a href="chap-glossary.html#definitions-8"><i class="fa fa-check"></i><b>20.10.1</b> Definitions</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Probability and Statistics: Making Principled Decisions in an Uncertain World</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-hypothesis-testing" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Hypothesis Testing<a href="chap-hypothesis-testing.html#chap-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Statistical inference allows us to use data to learn about the world in a rigorous way. In the previous chapter, we explored <strong>confidence intervals</strong> as one approach to inference, where we use a sample to construct an interval that will contain a population parameter with a stated 'confidence'. In this chapter, we turn to a second major inferential tool: <strong>hypothesis testing</strong>. This approach is commonly used when a researcher has a specific claim or question &lt;--about a population characteristic and wishes to assess whether the available data provide strong evidence for or against that claim.</p>
<!--## The Idea of a Hypothesis Test-->
<p>The idea is superficially simple (though you'll find that the topic is deep enough that it will take a while to grasp all the concepts). Suppose there is a claim you are interested exploring. This claim is either true or false, but you do not know which at this point. A sensible approach would be to gather evidence and make an informed decision.</p>
<p>Throughout this chapter, we will develop the hypothesis testing framework for the population mean (<span class="math inline">\(\mu\)</span>), matched pairs (<span class="math inline">\(\mu_D\)</span>), proportion (<span class="math inline">\(p\)</span>), and variance (<span class="math inline">\(\sigma^2\)</span>).
<!--## The Idea of a Hypothesis Test--></p>
<div id="logic-and-language-of-hypothesis-testing" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Logic and Language of Hypothesis Testing<a href="chap-hypothesis-testing.html#logic-and-language-of-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When conducting a hypothesis test, we begin by formulating two competing hypotheses:</p>
<ul>
<li>The <strong>null hypothesis</strong> (<span class="math inline">\(H_0\)</span>): our <em>reference</em> value which describes our current understanding about the parameter</li>
<li>The <strong><span id="def-alternative-hypothesis">alternative hypothesis</span></strong> (<span class="math inline">\(H_A\)</span>): an <em>interesting</em> new direction which would cause us to update our understanding about the parameter</li>
</ul>
<p>The approach we take is to <em>assume that the null hypothesis is true</em>, and then ask:</p>
<blockquote>
<p><em>How unusual is what we observed if <span class="math inline">\(H_0\)</span> were true?</em></p>
</blockquote>
<p>If what we observed is highly unlikely then either...</p>
<ul>
<li>We observed something very unusual; this can happen but it doesn't happen very often (by definition)</li>
<li>Our current understanding is flawed and should be revisited, causing us to reject <span class="math inline">\(H_0\)</span> in favor of <span class="math inline">\(H_A\)</span>.</li>
</ul>
<p>This framework is analogous to a legal court setting, where a person is presumed innocent unless the evidence against them is sufficiently compelling. Likewise, in hypothesis testing, we begin by assuming <span class="math inline">\(H_0\)</span> is true and only reject it if there is enough evidence in favor of <span class="math inline">\(H_A\)</span>.</p>
<p>Again, like the U.S. legal system, there are two components: the evidence and the legal standard of what constitutes enough evidence:</p>
<p><strong>The evidence:</strong></p>
<ol style="list-style-type: decimal">
<li><p>A <strong><span id="def-hypothesis-testing-test-statistic">test statistic</span>, <span class="math inline">\(T\)</span>,</strong> which quantifies how 'unusual' what we observed is from what we would expect if <span class="math inline">\(H_0\)</span> is true.</p></li>
<li><p>A <strong><span class="math inline">\(p\)</span>-value</strong>, which represents the probability, assuming <span class="math inline">\(H_0\)</span> is true, of obtaining a test statistic as large as the one we observed.</p></li>
</ol>
<p><strong>Enough evidence:</strong> We will compare these to...</p>
<ol style="list-style-type: decimal">
<li><p>a <strong>critical value</strong> as a threshold beyond which we consider the test statistic 'too unusual' to continue to assume <span class="math inline">\(H_0\)</span></p></li>
<li><p>an amount <strong><span class="math inline">\(\alpha\)</span></strong> whereby the <span class="math inline">\(p\)</span>-value being small enough means <span id="def-hypothesis-testing-p-value">p-value</span> <span class="math inline">\(&lt; \alpha\)</span>.</p></li>
</ol>
<p>This value <span class="math inline">\(\alpha\)</span> is very important and plays a major role in hypothesis testing, as we will see next. As well, it is the same <span class="math inline">\(\alpha\)</span> we already introduced in Confidence Intervals (e.g. Section <a href="chap-confidence-intervals.html#sec-CI-mean-known-sigma">9.3.2</a>). In fact, <span class="math inline">\(\alpha\)</span> always describes the same thing: the probability of being wrong.</p>
<p>The outcome of every hypothesis test ever is one of two possible decisions:</p>
<ul>
<li>Do not reject <span class="math inline">\(H_0\)</span>. We find that there is insufficient evidence to reject <span class="math inline">\(H_0\)</span>. Note that this is not saying that <span class="math inline">\(H_0\)</span> is true! Just we don't have evidence it is false.</li>
<li>Reject <span class="math inline">\(H_0\)</span>. We find that there is sufficient evidence against <span class="math inline">\(H_0\)</span> and we should update our understanding of the population parameter (and hence the scientific question of interest).</li>
</ul>
<p>Since there are two possible decisions and two possible outcomes for the hypothesis test (either the <span class="math inline">\(H_0\)</span> is true or <span class="math inline">\(H_A\)</span> is true), there is a 2x2 table describing the 4 possibilities.</p>
<div id="chap-ht-definitions" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> <span id="def-hypothesis-testing-type-i-error-type-1-error">Type I Error</span>, <span id="def-hypothesis-testing-type-ii-error-type-2-error">Type II error</span>, and <span id="def-hypothesis-testing-power">Power</span><a href="chap-hypothesis-testing.html#chap-ht-definitions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Whenever we perform a hypothesis test, we are making a decision based on incomplete information — and therefore, we are subject to making mistakes. The possible outcomes of a hypothesis test are summarized in the table below:</p>
<table>
<colgroup>
<col width="29%" />
<col width="34%" />
<col width="36%" />
</colgroup>
<thead>
<tr class="header">
<th>Decision</th>
<th><span class="math inline">\(H_0\)</span> True</th>
<th><span class="math inline">\(H_A\)</span> True</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Do not Reject <span class="math inline">\(H_0\)</span></td>
<td>✅ Correct</td>
<td>❌ <strong>Type II Error</strong></td>
</tr>
<tr class="even">
<td>Reject <span class="math inline">\(H_0\)</span></td>
<td>❌ <strong>Type I Error</strong></td>
<td>✅ Correct</td>
</tr>
</tbody>
</table>
<p>We define the two possible errors as follows:</p>
<ul>
<li><p><strong>Type I Error:</strong> Often called a 'false positive', a type I error is treated as the more serious of the two. Hence, we seek to control it. The probability of making a Type I error is denoted by <span class="math inline">\(\alpha\)</span> (alpha). This goes by the additional name the <strong><span id="def-hypothesis-testing-significance-level">significance level</span></strong>. This must be set in advance and is often <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li><p><strong>Type II Error:</strong> Often referred to as a 'false negative', a type II error indicates there wasn't enough evidence to reject <span class="math inline">\(H_0\)</span>, even though that would have been the correct decision.</p></li>
</ul>
<!-- probability of making a Type II error is denoted by $\beta$ (beta).-->
<p>The probability of a Type II error is more commonly described by its complement: <strong>power</strong></p>
<ul>
<li><strong>Power:</strong> The probability of correctly rejecting <span class="math inline">\(H_0\)</span>. It represents the sensitivity of the test in detecting an effect when there truly is one. Note that:</li>
</ul>
<p><span class="math display">\[
\text{Power} = 1 - P(\text{Type II error})
\]</span></p>
<!--Power is the probability of correctly rejecting $H_0$ when it is indeed false — in other words, the probability of making a correct decision when the alternative hypothesis is true.-->
<p>We will defer discussing power in more in depth until Section <a href="chap-hypothesis-testing.html#sec-HT-power">10.6</a></p>
<!--
- A **Type I Error** occurs when we reject the null hypothesis even though it is actually true.
- A **Type II Error** occurs when we fail to reject the null hypothesis even though it is actually false.


The probability of committing a Type I error is denoted by $\alpha$ and is also called the **significance level** of the test. This is typically set in advance, often at $\alpha = 0.05$.
-->
<!--
||                       | Actual Truth                                    |
| :-------------------------------- | :----------------------------------- | :-------------------------------- | :---------------------------------- |
||  | $H_0$ is True | $H_0$ is False |
|**Our Decision**| Reject $H_0$ | Type I Error           | Correct Decision |
|| Do not Reject $H_0$ | Correct Decision     | Type II Error              |
-->
</div>
</div>
<div id="sec-test-mean" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Hypothesis Test for a Population Mean<a href="chap-hypothesis-testing.html#sec-test-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section will mirror the results described in Section <a href="chap-confidence-intervals.html#sec-CI-mean">9.3</a>. Suppose we are planning to make a simple random sample of <span class="math inline">\(n\)</span> observations from a population: <span class="math inline">\(X_1, X_2, \dots, X_n\)</span>. We must assume (and/or check) that at least one of the following two conditions hold:</p>
<ul>
<li><span class="math inline">\(X_1, X_2, \dots, X_n \overset{\text{iid}}{\sim} N(\mu, \sigma^2)\)</span></li>
<li><span class="math inline">\(n\)</span> is large enough for the Central Limit Theorem (See Theorem <a href="chap-sampling-distributions.html#thm:clt">8.1</a>). For the purposes of this book, we can consider <span class="math inline">\(n \geq 30\)</span> to be large enough.</li>
</ul>
<p>In the following two sections, we will assume that at least one of these two conditions holds. When forming confidence intervals for <span class="math inline">\(\mu\)</span>, there are two important sub-cases:</p>
<ol style="list-style-type: decimal">
<li>The population standard deviation <span class="math inline">\(\sigma\)</span> is known (Section <a href="chap-hypothesis-testing.html#sec-HT-mean-known-sigma">10.2.1</a>)</li>
<li>The population standard deviation <span class="math inline">\(\sigma\)</span> is unknown (Section <a href="chap-hypothesis-testing.html#sec-HT-mean-unknown-sigma">10.2.2</a>).</li>
</ol>
<div id="sec-HT-mean-known-sigma" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> When <span class="math inline">\(\sigma\)</span> is known (Using the Normal Distribution)<a href="chap-hypothesis-testing.html#sec-HT-mean-known-sigma" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="sec-HT-mean-unknown-sigma" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> When <span class="math inline">\(\sigma\)</span> is unknown (Using the t Distribution)<a href="chap-hypothesis-testing.html#sec-HT-mean-unknown-sigma" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just as Section <a href="chap-confidence-intervals.html#sec-CI-mean-unknown-sigma">9.3.3</a> a <em>confidence interval</em> for the population mean, <span class="math inline">\(\mu\)</span>, when <span class="math inline">\(\sigma\)</span> is unknown, we now present a <em>hypothesis test</em> for the same scenario.</p>
<div class="colbox">
<div class="proposition">
<p><span id="prp:ht-pop-mean-t" class="proposition"><strong>Proposition 10.1  </strong></span>Let <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> meet either one of the conditions in Section <a href="chap-confidence-intervals.html#sec-samp-dist-normal">9.3.1</a> that make <span class="math inline">\(\bar{X}\)</span> have at least approximately a normal distribution. To test the hypotheses</p>
<p><span class="math display">\[
H_0 : \mu = \mu_0
\quad\text{vs.}\quad
H_A : \mu \neq \mu_0
\]</span></p>
<p>Here, as usual, <span class="math inline">\(\mu\)</span> is the unknown parameter and <span class="math inline">\(\mu_0\)</span> is a known value representing our existing knowledge about <span class="math inline">\(\mu\)</span>. Both of these values are constants.
Define the test statistic, <span class="math inline">\(T\)</span>, to be</p>
<p><span class="math display">\[
T = \frac{\bar{X} - \mu_0}{S/\sqrt{n}}
\]</span></p>
<p>where <span class="math inline">\(\bar{X}\)</span> and <span class="math inline">\(S\)</span> are the sample mean and sample standard deviation, respectively.</p>
<p>Assuming that the <span class="math inline">\(H_0\)</span> is true (that <span class="math inline">\(\mu\)</span> in fact equals <span class="math inline">\(\mu_0\)</span>), then<br />
<span class="math display">\[
T \sim t_{n-1}
\]</span></p>
<p>We will get an observed value of this test statistic, <span class="math inline">\(T_{obs}\)</span>:</p>
<p><span class="math display">\[
T_{obs} = \frac{\bar{x} - \mu_0}{s/\sqrt{n}}
\]</span>
where the values <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(s\)</span> are the observed values of the statistics we get from our experiment. It is now our task to decide: how much evidence does this number give against <span class="math inline">\(H_0\)</span>?</p>
<p>There will always be two equivalent ways to test a hypothesis. Reject <span class="math inline">\(H_0\)</span> if..</p>
<ul>
<li><strong>Critical Value</strong>: <span class="math inline">\(|T_{obs}| &gt; t_{\alpha/2, n-1}\)</span>, where $ t_{/2, n-1}$ is defined in Section <a href="chap-normal-distribution.html#sec-t-distribution">6.7</a>.</li>
<li><strong>p-value</strong>: p-value &lt; <span class="math inline">\(\alpha\)</span>.</li>
</ul>
</div>
</div>
<div class="whitebox">
<div class="example">
<p><span id="exm:ht-pop-mean-t-example" class="example"><strong>Example 10.1  </strong></span>Continuing the soup‐can study from Example <a href="chap-confidence-intervals.html#exm:ci-pop-mean-t-example">9.2</a>, suppose the manufacturer’s label now claims that the average sodium content is 830 mg per can. Recall that we had the following <span class="math inline">\(n = 12\)</span> sodium content measurements (in mg):</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="chap-hypothesis-testing.html#cb185-1" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">810</span>, <span class="dv">805</span>, <span class="dv">820</span>, <span class="dv">830</span>, <span class="dv">840</span>, <span class="dv">815</span>, <span class="dv">825</span>, <span class="dv">835</span>, <span class="dv">810</span>, <span class="dv">820</span>, <span class="dv">810</span>, <span class="dv">825</span>)</span></code></pre></div>
<p>We wish to test
<span class="math display">\[
H_0 : \mu = 830 \quad\text{vs.}\quad H_A : \mu \neq 830,
\]</span>
at the <span class="math inline">\(\alpha = 0.05\)</span> significance level.</p>
<p>The following <code>R</code> code computes the test statistic:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="chap-hypothesis-testing.html#cb186-1" tabindex="-1"></a>alpha  <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb186-2"><a href="chap-hypothesis-testing.html#cb186-2" tabindex="-1"></a>n      <span class="ot">=</span> <span class="fu">length</span>(x)</span>
<span id="cb186-3"><a href="chap-hypothesis-testing.html#cb186-3" tabindex="-1"></a>xbar   <span class="ot">=</span> <span class="fu">mean</span>(x)</span>
<span id="cb186-4"><a href="chap-hypothesis-testing.html#cb186-4" tabindex="-1"></a>s      <span class="ot">=</span> <span class="fu">sd</span>(x)</span>
<span id="cb186-5"><a href="chap-hypothesis-testing.html#cb186-5" tabindex="-1"></a>mu0    <span class="ot">=</span> <span class="dv">830</span></span>
<span id="cb186-6"><a href="chap-hypothesis-testing.html#cb186-6" tabindex="-1"></a>Tobs <span class="ot">=</span> (xbar <span class="sc">-</span> mu0) <span class="sc">/</span> (s <span class="sc">/</span> <span class="fu">sqrt</span>(n))</span>
<span id="cb186-7"><a href="chap-hypothesis-testing.html#cb186-7" tabindex="-1"></a>Tobs</span></code></pre></div>
<pre><code>## [1] -3.027174</code></pre>
<p>To make our decision regarding <span class="math inline">\(H_0\)</span>, we can either compute a p-value and reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\text{p-value} &lt; \alpha\)</span>, or, equivalently, we can reject <span class="math inline">\(H_0\)</span> if the test statistic exceeds in absolute value the associated critical value.</p>
<p>Let's look at these options via a plot:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-74-1.png" alt="" width="672" /></p>
<p>The p-value is probability of observing a value from the <span class="math inline">\(t_{n-1}\)</span> distribution that is at least as large as our observed test statistic. In other words, how unusual is the <span class="math inline">\(T_{obs}\)</span> that we got?</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="chap-hypothesis-testing.html#cb188-1" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fu">abs</span>(Tobs), n <span class="sc">-</span> <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] 0.01150728</code></pre>
<p>Because the p-value is less than <span class="math inline">\(\alpha = 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>. We have sufficient evidence to conclude that the population mean <span class="math inline">\(\mu\)</span>, whatever value it may be, is not equal to <span class="math inline">\(\mu_0 = 830\)</span>.</p>
<p>We can additionally compare <span class="math inline">\(T_{obs}\)</span> to the appropriate critical value: <span class="math inline">\(t_{.025, 11}\)</span>:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="chap-hypothesis-testing.html#cb190-1" tabindex="-1"></a>cVal <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb190-2"><a href="chap-hypothesis-testing.html#cb190-2" tabindex="-1"></a>cVal</span></code></pre></div>
<pre><code>## [1] 2.200985</code></pre>
<p>Because the absolute value of our observed test statistic is greater than this critical value, we come to the same conclusion: reject <span class="math inline">\(H_0\)</span>.</p>
</div>
</div>
<p>The built-in <code>R</code> function <code>t.test</code> conducts the above one-sample <span class="math inline">\(t\)</span>-test (and constructs the confidence interval that we manually computed in Example <a href="chap-confidence-intervals.html#exm:ci-pop-mean-t-example">9.2</a>):</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="chap-hypothesis-testing.html#cb192-1" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> mu0, <span class="at">conf.level =</span> <span class="dv">1</span><span class="sc">-</span>alpha)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = -3.0272, df = 11, p-value = 0.01151
## alternative hypothesis: true mean is not equal to 830
## 95 percent confidence interval:
##  813.4489 827.3845
## sample estimates:
## mean of x 
##  820.4167</code></pre>
<p>Notice the consistency between the 95% confidence interval for <span class="math inline">\(\mu\)</span> and the outcome of our two-sided test regarding <span class="math inline">\(\mu\)</span>. In particular, we rejected <span class="math inline">\(H_0: \mu = 830\)</span> with 95% confidence <em>and</em> 830 was not contained in the 95% confidence interval for <span class="math inline">\(\mu\)</span>. We can think of a confidence interval as representing a range of values for the target parameter that, with <span class="math inline">\((1 - \alpha) \times 100\)</span>% confidence, are consistent with our observed data. In other words, if a value is <em>not</em> contained in a <span class="math inline">\((1 - \alpha) \times 100\)</span>% confidence interval, then we are <span class="math inline">\((1 - \alpha) \times 100\)</span>% confident that the parameter does not equal that value. That is, in general, the results of a hypothesis test will be consistent with the analogous confidence interval: if the p-value is less than <span class="math inline">\(\alpha\)</span>, then the null-hypothesized parameter value will not be contained in the analogous <span class="math inline">\((1 - \alpha) \times 100\)</span>% confidence interval, and vice-versa.</p>
</div>
</div>
<div id="hypothesis-test-for-matched-pairs" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Hypothesis Test for Matched Pairs<a href="chap-hypothesis-testing.html#hypothesis-test-for-matched-pairs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Following the structure outlined in <a href="chap-confidence-intervals.html#sec-CI-matchedPairs">9.4</a>, we will extend the results for <strong>matched</strong> or <strong>paired</strong> experiments to the hypothesis testing paradigm.</p>
<div class="colbox">
<div class="proposition">
<p><span id="prp:ht-matched-pairs" class="proposition"><strong>Proposition 10.2  </strong></span>Let <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> and <span class="math inline">\(Y_1, Y_2, \ldots, Y_n\)</span> be measurements that are naturally <strong>paired</strong> with <span class="math inline">\(n \geq 30\)</span>. We wish to test the hypotheses</p>
<p><span class="math display">\[
H_0 : \mu_D = \Delta_0
\quad\text{vs.}\quad
H_A : \mu_D \neq \Delta_0
\]</span></p>
<p>Here, as usual, <span class="math inline">\(\mu_D\)</span> is the unknown parameter and <span class="math inline">\(\Delta_0\)</span> is a known value representing our existing knowledge about <span class="math inline">\(\mu_D\)</span>. In almost every case, <span class="math inline">\(\Delta_0 = 0\)</span>.</p>
<p>Define the test statistic, <span class="math inline">\(T\)</span>, to be</p>
<p><span class="math display">\[
T = \frac{\bar{D} - \Delta_0}{S_D/\sqrt{n}}
\]</span></p>
<p>where <span class="math inline">\(\bar{D}\)</span> and <span class="math inline">\(S_D\)</span> are the sample mean and sample standard deviation, respectively, of the differences.</p>
<p>Assuming that the <span class="math inline">\(H_0\)</span> is true (that <span class="math inline">\(\mu_D\)</span> in fact equals <span class="math inline">\(\Delta_0\)</span>), then<br />
<span class="math display">\[
T \sim t_{n-1}
\]</span></p>
<p>We will get an observed value of this test statistic, <span class="math inline">\(T_{obs}\)</span>:</p>
<p><span class="math display">\[
T_{obs} = \frac{\bar{d} - \Delta_0}{s_D/\sqrt{n}}
\]</span>
where the values <span class="math inline">\(\bar{d}\)</span> and <span class="math inline">\(s_D\)</span> are the observed values of the statistics we get from our experiment. It is now our task to decide: how much evidence does this number give against <span class="math inline">\(H_0\)</span>?</p>
<p>There will always be two equivalent ways to test a hypothesis. Reject <span class="math inline">\(H_0\)</span> if..</p>
<ul>
<li><strong>Critical Value</strong>: <span class="math inline">\(|T_{obs}| &gt; t_{\alpha/2, n-1}\)</span>, where <span class="math inline">\(t_{\alpha/2, n-1}\)</span> is defined in Section <a href="chap-normal-distribution.html#sec-t-distribution">6.7</a>.</li>
<li><strong>p-value</strong>: p-value &lt; <span class="math inline">\(\alpha\)</span>.</li>
</ul>
</div>
</div>
<p>Let's return to the example <a href="chap-confidence-intervals.html#exm:ci-matched-pairs-summary-stats">9.3</a>.</p>
<p><em>Solution</em>: For <span class="math inline">\(\alpha\)</span> = 0.05 and <span class="math inline">\(\Delta_0 = 0\)</span>, we will reject the null hypothesis that the mean difference is 0 if</p>
<p><span class="math display">\[
|T| &gt; 2.0452 = t_{.025,29}
\]</span>
To emphasize: this is our plan, we must now conduct the experiment and make our decision.</p>
<p><em>Back to the problem statement</em>: Now, we actually conduct our experiment and collect a simple random sample <span class="math inline">\(n = 30\)</span> customers. We find for design 1, a sample average of $4.98 and for design 2 a sample average of $4.23. Hence, <span class="math inline">\(\overline{d} = \$0.75\)</span>. As well, after finding the differences <span class="math inline">\(d_i\)</span>, we find that the sample standard deviation of the difference is <span class="math inline">\(s_d\)</span> = $0.9.</p>
<p><em>Back to the solution</em>: We calculate our observed test statistic:</p>
<p><span class="math display">\[
T_{obs} = \frac{0.75}{0.9/\sqrt{30}} = 4.5644
\]</span>
which, absolute value, gets compared to 2.0452. Hence, we reject <span class="math inline">\(H_0\)</span> and find that there is sufficient evidence to conclude that the bottles design have a different price, on average.</p>
<p>:::
::::</p>
<p>The above method is usable when we are only given the <strong>summary statistics</strong>, e.g. the sample averages. There is another, sleeker way if we have the actual measurements, again using the very useful function <code>t.test</code>:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="chap-hypothesis-testing.html#cb194-1" tabindex="-1"></a>alpha <span class="ot">=</span> .<span class="dv">02</span></span>
<span id="cb194-2"><a href="chap-hypothesis-testing.html#cb194-2" tabindex="-1"></a></span>
<span id="cb194-3"><a href="chap-hypothesis-testing.html#cb194-3" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">884</span>,<span class="dv">806</span>,<span class="dv">885</span>,<span class="dv">873</span>,<span class="dv">813</span>,<span class="dv">835</span>,<span class="dv">818</span>,<span class="dv">884</span>,<span class="dv">896</span>,<span class="dv">873</span>,<span class="dv">828</span>,<span class="dv">845</span>,<span class="dv">898</span>,<span class="dv">810</span>,<span class="dv">884</span>,<span class="dv">818</span>,<span class="dv">834</span>,</span>
<span id="cb194-4"><a href="chap-hypothesis-testing.html#cb194-4" tabindex="-1"></a>      <span class="dv">823</span>,<span class="dv">890</span>,<span class="dv">878</span>,<span class="dv">813</span>,<span class="dv">804</span>,<span class="dv">822</span>,<span class="dv">818</span>,<span class="dv">809</span>,<span class="dv">829</span>,<span class="dv">829</span>,<span class="dv">873</span>,<span class="dv">807</span>,<span class="dv">813</span>)</span>
<span id="cb194-5"><a href="chap-hypothesis-testing.html#cb194-5" tabindex="-1"></a>y <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">901</span>,<span class="dv">885</span>,<span class="dv">834</span>,<span class="dv">908</span>,<span class="dv">903</span>,<span class="dv">825</span>,<span class="dv">857</span>,<span class="dv">833</span>,<span class="dv">892</span>,<span class="dv">824</span>,<span class="dv">855</span>,<span class="dv">837</span>,<span class="dv">843</span>,<span class="dv">849</span>,<span class="dv">907</span>,<span class="dv">848</span>,<span class="dv">851</span>,</span>
<span id="cb194-6"><a href="chap-hypothesis-testing.html#cb194-6" tabindex="-1"></a>      <span class="dv">886</span>,<span class="dv">864</span>,<span class="dv">900</span>,<span class="dv">869</span>,<span class="dv">864</span>,<span class="dv">877</span>,<span class="dv">842</span>,<span class="dv">914</span>,<span class="dv">915</span>,<span class="dv">826</span>,<span class="dv">870</span>,<span class="dv">821</span>,<span class="dv">885</span>)</span>
<span id="cb194-7"><a href="chap-hypothesis-testing.html#cb194-7" tabindex="-1"></a></span>
<span id="cb194-8"><a href="chap-hypothesis-testing.html#cb194-8" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">conf.level=</span><span class="dv">1</span><span class="sc">-</span>alpha)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  x and y
## t = -2.894, df = 29, p-value = 0.007151
## alternative hypothesis: true mean difference is not equal to 0
## 98 percent confidence interval:
##  -42.751673  -3.448327
## sample estimates:
## mean difference 
##           -23.1</code></pre>
<p>Note that the output provides both a 98% confidence interval and a hypothesis test
with <span class="math inline">\(\alpha = 0.02\)</span>.</p>
</div>
<div id="sec-HT-proportion" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Hypothesis Test for a Population Proportion<a href="chap-hypothesis-testing.html#sec-HT-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Referring to the motivation and notation from Section <a href="chap-confidence-intervals.html#sec-CI-proportion">9.5</a>, we now consider a hypothesis test about a population proportion <span class="math inline">\(p\)</span></p>
<div class="colbox">
<div class="proposition">
<p><span id="prp:ht-pop-proportion-z" class="proposition"><strong>Proposition 10.3  </strong></span>Let <span class="math inline">\(X\)</span> denote the number of "successes" observed in a random sample of size <span class="math inline">\(n\)</span>, and let <span class="math inline">\(\hat{p} = x / n\)</span> be the sample proportion. To test</p>
<p><span class="math display">\[
H_0 : p = p_0
\quad\text{vs.}\quad
H_A : p \neq p_0
\]</span></p>
<p>use the test statistic</p>
<p><span class="math display">\[
T = \frac{\hat{p} - p_0}
         {\sqrt{\dfrac{p_0(1-p_0)}{n}}}
\]</span></p>
<p>Provided the sample size is "large enough" (e.g., <span class="math inline">\(n\hat{p} \ge 10\)</span> and <span class="math inline">\(n(1 - \hat{p}) \ge 10\)</span>),</p>
<p><span class="math display">\[
T \;\sim\; N(0,1)
\text{ assuming that } H_0 \text{ is true}
\]</span></p>
<p>To test with Type I error <span class="math inline">\(\alpha\)</span>, reject <span class="math inline">\(H_0\)</span> if the p-value is less than <span class="math inline">\(\alpha\)</span>. Equivalently, reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|Z| &gt; z_{\alpha/2}\)</span>, where <span class="math inline">\(z_{\alpha/2}\)</span> is the <span class="math inline">\((1 - \alpha/2)\)</span> quantile of the standard Normal distribution.</p>
</div>
</div>
<div class="whitebox">
<div class="example">
<p><span id="exm:ht-pop-proportion-example" class="example"><strong>Example 10.2  </strong></span>Continuing with the marketing data from Example <a href="chap-confidence-intervals.html#exm:ci-pop-proportion-example">9.4</a>, suppose we wish to test whether the proportion of satisfied customers equals 0.75. Recall that we had a sample of <span class="math inline">\(n = 150\)</span> customers, of whom <span class="math inline">\(x = 117\)</span> reported that they were satisfied, corresponding to a sample proportion of <span class="math inline">\(\hat{p} = x / n = 0.78\)</span>.</p>
<p>We wish to test
<span class="math display">\[
H_0 : p = 0.75 \quad\text{vs.}\quad H_A : p \neq 0.75,
\]</span>
at the <span class="math inline">\(\alpha = 0.05\)</span> significance level. We confirmed in Example <a href="chap-confidence-intervals.html#exm:ci-pop-proportion-example">9.4</a> that the sample size is sufficient for us to apply the usual one-sample <span class="math inline">\(z\)</span>-based inferential methods.</p>
<p>The following <code>R</code> code computes the test statistic:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="chap-hypothesis-testing.html#cb196-1" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">150</span></span>
<span id="cb196-2"><a href="chap-hypothesis-testing.html#cb196-2" tabindex="-1"></a>x <span class="ot">=</span> <span class="dv">117</span></span>
<span id="cb196-3"><a href="chap-hypothesis-testing.html#cb196-3" tabindex="-1"></a>phat <span class="ot">=</span> x <span class="sc">/</span> n</span>
<span id="cb196-4"><a href="chap-hypothesis-testing.html#cb196-4" tabindex="-1"></a>p0 <span class="ot">=</span> <span class="fl">0.75</span></span>
<span id="cb196-5"><a href="chap-hypothesis-testing.html#cb196-5" tabindex="-1"></a>z_stat <span class="ot">=</span> (phat <span class="sc">-</span> p0) <span class="sc">/</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span>
<span id="cb196-6"><a href="chap-hypothesis-testing.html#cb196-6" tabindex="-1"></a>z_stat</span></code></pre></div>
<pre><code>## [1] 0.8485281</code></pre>
<p>The p-value is two times the probability of observing a value from the standard Normal distribution that is as or more extreme as the absolute value of our observed test statistic. That is,</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="chap-hypothesis-testing.html#cb198-1" tabindex="-1"></a>p_val <span class="ot">=</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_stat)))</span>
<span id="cb198-2"><a href="chap-hypothesis-testing.html#cb198-2" tabindex="-1"></a>p_val</span></code></pre></div>
<pre><code>## [1] 0.3961439</code></pre>
<p>Because the p-value is greater than <span class="math inline">\(\alpha = 0.05\)</span>, we "fail to reject" <span class="math inline">\(H_0\)</span>. In other words, with 95% confidence, <span class="math inline">\(0.75\)</span> cannot be excluded as a plausible value for <span class="math inline">\(p\)</span>.</p>
<p>The relevant critical value for comparison with the test statistic itself is <span class="math inline">\(z_{\alpha / 2} = z_{0.025}\)</span>:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="chap-hypothesis-testing.html#cb200-1" tabindex="-1"></a>z_alpha <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb200-2"><a href="chap-hypothesis-testing.html#cb200-2" tabindex="-1"></a>z_alpha</span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<p>Because the absolute value of our observed test statistic is not greater than this critical value, we come to the same conclusion: fail to reject <span class="math inline">\(H_0\)</span> (with 95% confidence).</p>
</div>
</div>
<p>The built-in <code>R</code> function <code>prop.test</code> conducts the above one-sample <span class="math inline">\(z\)</span>-test (and constructs the confidence interval that we manually computed in Example <a href="chap-confidence-intervals.html#exm:ci-pop-proportion-example">9.4</a>):</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="chap-hypothesis-testing.html#cb202-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> x, <span class="at">n =</span> n, <span class="at">p =</span> p0, <span class="at">conf.level =</span> <span class="fl">0.95</span>, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  x out of n, null probability p0
## X-squared = 0.72, df = 1, p-value = 0.3961
## alternative hypothesis: true p is not equal to 0.75
## 95 percent confidence interval:
##  0.7071769 0.8388398
## sample estimates:
##    p 
## 0.78</code></pre>
<p>In order to match our manually-calculated p-value, we set the <code>correct</code> argument in <code>prop.test</code> to <code>FALSE</code>; this argument controls whether a "continuity correction" is applied to adjust for the fact that we are using a continuous probability distribution (the Normal distribution) to approximate a discrete distribution (the Binomial distribution).</p>
<div id="hypothesis-test-for-a-population-variance" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Hypothesis Test for a Population Variance<a href="chap-hypothesis-testing.html#hypothesis-test-for-a-population-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Returning to the Section <a href="chap-confidence-intervals.html#sec-CI-variance">9.6</a> context of inference on a population variance, we now consider a hypothesis test about a population variance.</p>
<div class="colbox">
<div class="proposition">
<p><span id="prp:ht-pop-variance" class="proposition"><strong>Proposition 10.4  </strong></span>Let <span class="math inline">\(X_1, X_2, \dots, X_n \overset{\text{iid}}{\sim} \mathcal{N}(\mu, \sigma^2)\)</span> and let <span class="math inline">\(S^2\)</span> denote the sample variance. To test</p>
<p><span class="math display">\[
H_0 : \sigma^2 = \sigma_0^2
\quad\text{vs.}\quad
H_A : \sigma^2 \neq \sigma_0^2
\]</span></p>
<p>define the test statistic</p>
<p><span class="math display">\[
\chi^2 = \frac{(n - 1) S^2}{\sigma_0^2}
\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic follows a chi-squared distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom:</p>
<p><span class="math display">\[
\chi^2 \sim \chi^2_{n - 1}
\]</span></p>
<p>To test with significance level <span class="math inline">\(\alpha\)</span>, reject <span class="math inline">\(H_0\)</span> if the p-value is less than <span class="math inline">\(\alpha\)</span>. Equivalently, reject <span class="math inline">\(H_0\)</span> if
<span class="math display">\[
  \chi^2 &lt; \chi^2_{1 - \alpha/2, \; n - 1}
  \quad\text{or}\quad
  \chi^2 &gt; \chi^2_{\alpha/2, \; n - 1}
  \]</span>
where <span class="math inline">\(\chi^2_{\alpha/2, n - 1}\)</span> and <span class="math inline">\(\chi^2_{1-\alpha/2, n-1}\)</span> denote the <span class="math inline">\((1 - \alpha/2)\)</span> and <span class="math inline">\(\alpha/2\)</span> quantiles, respectively, of the <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom.</p>
</div>
</div>
<div class="whitebox">
<div class="example">
<p><span id="exm:ht-pop-proportion-example" class="example"><strong>Example 10.2  </strong></span>Continuing with the chemistry data from Example <a href="chap-confidence-intervals.html#exm:ci-pop-variance-example">9.5</a>, suppose we wish to test <span class="math inline">\(H_0: \sigma^2 = 0.10\)</span> vs. the <em>one-sided</em> alternative <span class="math inline">\(H_A: \sigma^2 &gt; 0.10\)</span> at significance level <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="chap-hypothesis-testing.html#cb204-1" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.9</span>, <span class="fl">5.4</span>, <span class="fl">5.2</span>, <span class="fl">5.0</span>, <span class="fl">4.8</span>, <span class="fl">5.3</span>, <span class="fl">5.2</span>)</span>
<span id="cb204-2"><a href="chap-hypothesis-testing.html#cb204-2" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(x)</span>
<span id="cb204-3"><a href="chap-hypothesis-testing.html#cb204-3" tabindex="-1"></a>s2 <span class="ot">=</span> <span class="fu">var</span>(x)</span>
<span id="cb204-4"><a href="chap-hypothesis-testing.html#cb204-4" tabindex="-1"></a>s2_0 <span class="ot">=</span> <span class="fl">0.10</span></span></code></pre></div>
<p>The following <code>R</code> code computes the test statistic, p-value, and critical value:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="chap-hypothesis-testing.html#cb205-1" tabindex="-1"></a>tesTobs <span class="ot">=</span> (n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> s2 <span class="sc">/</span> s2_0</span>
<span id="cb205-2"><a href="chap-hypothesis-testing.html#cb205-2" tabindex="-1"></a>p_val <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(tesTobs, n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb205-3"><a href="chap-hypothesis-testing.html#cb205-3" tabindex="-1"></a>crit_val <span class="ot">=</span> <span class="fu">qchisq</span>(<span class="fl">0.99</span>, n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb205-4"><a href="chap-hypothesis-testing.html#cb205-4" tabindex="-1"></a>tesTobs</span></code></pre></div>
<pre><code>## [1] 2.8875</code></pre>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="chap-hypothesis-testing.html#cb207-1" tabindex="-1"></a>p_val</span></code></pre></div>
<pre><code>## [1] 0.8952106</code></pre>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="chap-hypothesis-testing.html#cb209-1" tabindex="-1"></a>crit_val</span></code></pre></div>
<pre><code>## [1] 18.47531</code></pre>
<p>Note that, because of the form of the alternative hypothesis, evidence against <span class="math inline">\(H_0\)</span> looks like <em>large</em> test statistic values. That is, the p-value is the probability, under <span class="math inline">\(H_0\)</span>, of observing a test statistic value <em>greater than</em> our observed test statistic value (a "one-tailed" probability). Similarly, there is a single critical value, <span class="math inline">\(\chi^2_{1 - \alpha, n-1} = \chi^2_{0.01, n-1}\)</span>, equal to the 99th percentile of the <span class="math inline">\(\chi^2_{n-1}\)</span> distribution.</p>
<p>Because the p-value is greater than <span class="math inline">\(\alpha = 0.01\)</span> and the test statistic is less than the critical value, we fail to reject <span class="math inline">\(H_0\)</span> (with 99% confidence).</p>
</div>
</div>
<p>There is no built-in <code>R</code> function (like <code>t.test</code> and <code>prop.test</code>) for doing the above test for a population variance.</p>
</div>
</div>
<div id="sec-HT-one-vs-two" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Two-sided and One-sided Tests<a href="chap-hypothesis-testing.html#sec-HT-one-vs-two" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A key aspect of hypothesis testing is that it can be customized to match the scientific question of interest. The variety of parameters we just discussed is one way. Another is in the form for the alternative hypothesis. There are three options:</p>
<p><strong>Two-sided:</strong> If the scientifically interesting result would be to detect a <em>change</em> in the parameter from your existing understanding (e.g. <span class="math inline">\(\mu_0\)</span> or <span class="math inline">\(p_0\)</span>), then you should phrase the hypothesis as two-sided:</p>
<p><span class="math display">\[
H_0 : \mu = \mu_0
\quad\text{vs.}\quad
H_A : \mu \neq \mu_0
\]</span></p>
<p>In this case, you look for evidence in the test statistic being unusually large in magnitude:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-86"></span>
<img src="_main_files/figure-html/unnamed-chunk-86-1.png" alt="Example of a two-sided hypothesis test." width="672" />
<p class="caption">
Figure 10.1: Example of a two-sided hypothesis test.
</p>
</div>
<p>In the above plot, the observed test statistic <span class="math inline">\(T_{obs}\)</span> = -3.027. We would (and did in this case) reject since <span class="math inline">\(|T_{obs}| &gt; t_{\alpha/2, n-1}\)</span> = 2.718..</p>
<p>Similarly, we compute the p-value <span class="math inline">\(P(T &lt; T_{obs} \text{ or } T &gt; T_{obs}) = 2\cdot P(T &gt; |T_{obs}|)\)</span>:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="chap-hypothesis-testing.html#cb211-1" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fu">abs</span>(Tobs),n<span class="dv">-1</span>))</span></code></pre></div>
<pre><code>## [1] 0.01150728</code></pre>
<p>We have conducted this test with <span class="math inline">\(\alpha\)</span> = 0.02, which should be compared to the p-value. As always, we will reject when this p-value is too small: p-value &lt; <span class="math inline">\(\alpha\)</span>. Again, we would decide to reject <span class="math inline">\(H_0\)</span>.</p>
<ul>
<li><strong>One-sided <span class="math inline">\(&lt;\)</span>:</strong> If the scientifically interesting result would be to detect a <em>decrease</em> in the parameter from your existing understanding (e.g. <span class="math inline">\(\mu_0\)</span> or <span class="math inline">\(p_0\)</span>), then you should phrase the hypothesis as:
<span class="math display">\[
H_0 : \mu \geq \mu_0
\quad\text{vs.}\quad
H_A : \mu &lt; \mu_0
\]</span></li>
</ul>
<p>In this case, you look for evidence in the test statistic being unusually small (in the negative direction):</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-88"></span>
<img src="_main_files/figure-html/unnamed-chunk-88-1.png" alt="Example of a one-sided $&lt;$ hypothesis test." width="672" />
<p class="caption">
Figure 10.2: Example of a one-sided <span class="math inline">\(&lt;\)</span> hypothesis test.
</p>
</div>
<p>In the above plot, the observed test statistic <span class="math inline">\(T_{obs}\)</span> = -3.027. We would (and did in this case) reject since <span class="math inline">\(T_{obs} &lt; - t_{\alpha, n-1}\)</span> = -2.328..</p>
<p>Similarly, we compute the p-value via <span class="math inline">\(P(T &lt; T_{obs})\)</span>:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="chap-hypothesis-testing.html#cb213-1" tabindex="-1"></a><span class="fu">pt</span>(Tobs,n<span class="dv">-1</span>)</span></code></pre></div>
<pre><code>## [1] 0.005753638</code></pre>
<p>We have conducted this test with <span class="math inline">\(\alpha\)</span> = 0.02, which should be compared to the p-value. As always, we will reject when this p-value is too small: p-value &lt; <span class="math inline">\(\alpha\)</span>. Again, we would decide to reject <span class="math inline">\(H_0\)</span>.</p>
<ul>
<li><strong>One-sided <span class="math inline">\(&gt;\)</span>:</strong> If the scientifically interesting result would be to detect an <em>increase</em> in the parameter from your existing understanding (e.g. <span class="math inline">\(\mu_0\)</span> or <span class="math inline">\(p_0\)</span>), then you should phrase the hypothesis as:
<span class="math display">\[
H_0 : \mu \leq \mu_0
\quad\text{vs.}\quad
H_A : \mu &gt; \mu_0
\]</span></li>
</ul>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-90"></span>
<img src="_main_files/figure-html/unnamed-chunk-90-1.png" alt="Example of a one-sided $&gt;$ hypothesis test." width="672" />
<p class="caption">
Figure 10.3: Example of a one-sided <span class="math inline">\(&gt;\)</span> hypothesis test.
</p>
</div>
<p>In the above plot, the observed test statistic <span class="math inline">\(T_{obs}\)</span> = -3.027. We would (but did <strong>not</strong> in this case) reject if <span class="math inline">\(T_{obs} &gt; t_{\alpha, n-1}\)</span> = 2.328.</p>
<p>Similarly, we compute the p-value via <span class="math inline">\(P(T &gt; T_{obs}) = P(T &gt; T_{obs})\)</span></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="chap-hypothesis-testing.html#cb215-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(Tobs,n<span class="dv">-1</span>)</span></code></pre></div>
<pre><code>## [1] 0.9942464</code></pre>
<p>We have conducted this test with <span class="math inline">\(\alpha\)</span> = 0.02, which should be compared to the p-value. As always, we will reject when this p-value is too small: p-value &lt; <span class="math inline">\(\alpha\)</span>. We would decide not to reject <span class="math inline">\(H_0\)</span> as 0.9942464 &gt; 0.02.</p>
<p><strong>Comment:</strong> This example deserves more explanation. It would be unusual to get a negative <span class="math inline">\(T_{obs}\)</span> when doing a one-sided <span class="math inline">\(&gt;\)</span> test. However, if we did, this would be the result</p>
</div>
<div id="sec-HT-power" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Power<a href="chap-hypothesis-testing.html#sec-HT-power" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!--\@ref(sec-CI-mean-unknown-sigma)-->
<p>Recall the definition of power as it relates to hypothesis testing. Power = <span class="math inline">\(1 - P(\text{Type II error})\)</span> is the probability of rejecting <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_0\)</span> is false. Though the concept of power applies to all hypothesis tests, we will mainly focus on the <span class="math inline">\(\mu\)</span> with <span class="math inline">\(\sigma\)</span> known case (Section <a href="chap-hypothesis-testing.html#sec-HT-mean-known-sigma">10.2.1</a>) Hence, power will depend on several factors:</p>
<ul>
<li>How 'false' is <span class="math inline">\(H_0\)</span>?. Considering values for the parameter 'close' vs. 'far' from <span class="math inline">\(H_0\)</span>.</li>
<li>The sample size <span class="math inline">\(n\)</span>.</li>
<li>The population standard deviation.</li>
<li>The chosen significance level <span class="math inline">\(\alpha\)</span>.</li>
</ul>
<p>Power is an essential consideration in the design of studies and in fact is used in concert with the results about choosing the sample size in Section <a href="#sec-precision-sample-size"><strong>??</strong></a>. Researchers often want to ensure that they have a sufficiently high probability of detecting an effect, if one exists. This is often accomplished via <strong>sample size calculations</strong>, which we will return to shortly.</p>
<p>Below, is the <strong>power curve</strong> of our test from the above simulation for a range of possible values of <span class="math inline">\(\mu\)</span>: Let's define a function:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="chap-hypothesis-testing.html#cb217-1" tabindex="-1"></a><span class="co"># Function to compute values for a given value of mu</span></span>
<span id="cb217-2"><a href="chap-hypothesis-testing.html#cb217-2" tabindex="-1"></a>get_pvals <span class="ot">=</span> <span class="cf">function</span>(mu_true) {</span>
<span id="cb217-3"><a href="chap-hypothesis-testing.html#cb217-3" tabindex="-1"></a>  <span class="fu">replicate</span>(num_sims, {</span>
<span id="cb217-4"><a href="chap-hypothesis-testing.html#cb217-4" tabindex="-1"></a>    x <span class="ot">=</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu_true, <span class="at">sd =</span> sigma)</span>
<span id="cb217-5"><a href="chap-hypothesis-testing.html#cb217-5" tabindex="-1"></a>    xbar <span class="ot">=</span> <span class="fu">mean</span>(x)</span>
<span id="cb217-6"><a href="chap-hypothesis-testing.html#cb217-6" tabindex="-1"></a>    se <span class="ot">=</span> sigma <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb217-7"><a href="chap-hypothesis-testing.html#cb217-7" tabindex="-1"></a>    <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(xbar), <span class="at">mean =</span> mu_null, <span class="at">sd =</span> se))</span>
<span id="cb217-8"><a href="chap-hypothesis-testing.html#cb217-8" tabindex="-1"></a>  })</span>
<span id="cb217-9"><a href="chap-hypothesis-testing.html#cb217-9" tabindex="-1"></a>}</span>
<span id="cb217-10"><a href="chap-hypothesis-testing.html#cb217-10" tabindex="-1"></a></span>
<span id="cb217-11"><a href="chap-hypothesis-testing.html#cb217-11" tabindex="-1"></a>n        <span class="ot">=</span> <span class="dv">15</span></span>
<span id="cb217-12"><a href="chap-hypothesis-testing.html#cb217-12" tabindex="-1"></a>sigma    <span class="ot">=</span> <span class="fl">1.4</span></span>
<span id="cb217-13"><a href="chap-hypothesis-testing.html#cb217-13" tabindex="-1"></a>mu_null  <span class="ot">=</span> <span class="fl">5.0</span></span>
<span id="cb217-14"><a href="chap-hypothesis-testing.html#cb217-14" tabindex="-1"></a>mu_alt   <span class="ot">=</span> <span class="fl">5.25</span></span>
<span id="cb217-15"><a href="chap-hypothesis-testing.html#cb217-15" tabindex="-1"></a>alpha    <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb217-16"><a href="chap-hypothesis-testing.html#cb217-16" tabindex="-1"></a>num_sims <span class="ot">=</span> <span class="dv">10000</span></span></code></pre></div>
<p>Then</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="chap-hypothesis-testing.html#cb218-1" tabindex="-1"></a>mu_vals <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">5</span>, <span class="dv">7</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb218-2"><a href="chap-hypothesis-testing.html#cb218-2" tabindex="-1"></a>powers <span class="ot">=</span> <span class="fu">sapply</span>(mu_vals, <span class="cf">function</span>(mu) <span class="fu">mean</span>(<span class="fu">get_pvals</span>(mu) <span class="sc">&lt;</span> alpha))</span>
<span id="cb218-3"><a href="chap-hypothesis-testing.html#cb218-3" tabindex="-1"></a></span>
<span id="cb218-4"><a href="chap-hypothesis-testing.html#cb218-4" tabindex="-1"></a><span class="fu">plot</span>(mu_vals, powers, <span class="at">type =</span> <span class="st">&quot;b&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb218-5"><a href="chap-hypothesis-testing.html#cb218-5" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">expression</span>(mu), <span class="at">ylab =</span> <span class="st">&quot;Power&quot;</span>,</span>
<span id="cb218-6"><a href="chap-hypothesis-testing.html#cb218-6" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Power Curve&quot;</span>)</span>
<span id="cb218-7"><a href="chap-hypothesis-testing.html#cb218-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> alpha, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:power-curve"></span>
<img src="_main_files/figure-html/power-curve-1.png" alt="Power Curve for Simulation Context" width="624" />
<p class="caption">
Figure 10.4: Power Curve for Simulation Context
</p>
</div>
<p>This <strong>power curve</strong> shows how the probability of correctly rejecting <span class="math inline">\(H_0\)</span> increases as the true mean <span class="math inline">\(\mu\)</span> deviates further from the null value of 5. The red dashed line marks the significance level <span class="math inline">\(\alpha = 0.05\)</span>. Notice that the "power" to detect <span class="math inline">\(\mu = 5\)</span> (the null-hypothesized value of <span class="math inline">\(\mu\)</span>) is approximately equal to <span class="math inline">\(\alpha = 0.05\)</span>. This is by design: we have engineered our testing protocol such that we tolerate at most <span class="math inline">\(\alpha = 0.05\)</span> probability of making a Type I error.</p>
<div id="sample-size-calculation-for-desired-power" class="section level4 hasAnchor" number="10.6.0.1">
<h4><span class="header-section-number">10.6.0.1</span> Sample Size Calculation for Desired Power<a href="chap-hypothesis-testing.html#sample-size-calculation-for-desired-power" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let us now explore how we can determine the sample size <span class="math inline">\(n\)</span> required to achieve a desired power to detect a particular alternative mean value. In the context of our ongoing simulation study, recall that we are testing:</p>
<p><span class="math display">\[
H_0: \mu = 5 \quad \text{vs.} \quad H_A: \mu \neq 5
\]</span></p>
<p>Suppose we wish to ensure that our hypothesis test has 80% power (i.e., Type II error rate <span class="math inline">\(\beta = 0.2\)</span>) to detect an alternative value <span class="math inline">\(\mu = 5.75\)</span>. In other words, if the true population mean were 5.75, we want to have an 80% chance of rejecting <span class="math inline">\(H_0\)</span>.</p>
<p>In our earlier setup, we used the sample mean <span class="math inline">\(\bar{x}\)</span> as the test statistic. We noted that, assuming the null hypothesis is true, the sampling distribution of <span class="math inline">\(\bar{x}\)</span> is:</p>
<p><span class="math display">\[
\bar{X} \overset{H_0}{\sim} N\left(5, \frac{1.4}{\sqrt{n}}\right)
\]</span></p>
<p>Under the alternative <span class="math inline">\(\mu = 5.75\)</span>, the distribution of <span class="math inline">\(\bar{x}\)</span> becomes:</p>
<p><span class="math display">\[
\bar{X} \overset{H_A}{\sim} N\left(5.75, \frac{1.4}{\sqrt{n}}\right)
\]</span></p>
<p>To achieve 80% power, we want 80% of the sampling distribution under the alternative (centered at 5.75) to fall outside the null hypothesis’s <strong><span id="def-hypothesis-testing-rejection-region">rejection region</span></strong> — that is, the range of <span class="math inline">\(\bar{x}\)</span> values we would consider “too unlikely” under <span class="math inline">\(H_0\)</span>.</p>
<p>In a two-sided test with significance level <span class="math inline">\(\alpha = 0.05\)</span>, the rejection region corresponds to the values of <span class="math inline">\(\bar{x}\)</span> that lie in the outer 2.5% tails of the null distribution. That is, we reject <span class="math inline">\(H_0\)</span> if:</p>
<p><span class="math display">\[
\bar{x} &lt; \mu_0 - z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}} \quad \text{or} \quad
\bar{x} &gt; \mu_0 + z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>We can solve algebraically for the sample size <span class="math inline">\(n\)</span> required to achieve a given power. The resulting formula is:</p>
<p><span class="math display">\[
n = \left( \frac{z_{\alpha/2} + z_{\text{power}}}{\mu_a - \mu_0} \cdot \sigma \right)^2
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\mu_0 = 5\)</span> is the null-hypothesized mean,</li>
<li><span class="math inline">\(\mu_a = 5.75\)</span> is the alternative mean we wish to detect,</li>
<li><span class="math inline">\(\sigma = 1.4\)</span> is the population standard deviation,</li>
<li><span class="math inline">\(z_{\alpha/2} = 1.96\)</span> for a two-sided test at <span class="math inline">\(\alpha = 0.05\)</span> (<code>qnorm(0.975)</code>),</li>
<li><span class="math inline">\(z_{\text{power}} = 0.84\)</span> to achieve 80% power (<code>qnorm(0.80)</code>).</li>
</ul>
<p>Plugging in the numbers:</p>
<p><span class="math display">\[
n = \left( \frac{1.96 + 0.84}{0.75} \cdot 1.4 \right)^2 \approx 27.3
\]</span></p>
<p>So, we would need approximately <span class="math inline">\(n = 28\)</span> observations to have 80% power to detect that the true mean is 5.75, assuming we use <span class="math inline">\(\bar{x}\)</span> as our test statistic and the population standard deviation is known to be 1.4. Note that, since it is not possible to sample a fraction of an individual, we always <em>round up</em> to the nearest integer when computing sample size requirements.</p>
<p>The following figure shows power curves for our simulation context that correspond to a variety of sample sizes.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-93"></span>
<img src="_main_files/figure-html/unnamed-chunk-93-1.png" alt="Power Curves for Different Sample Sizes in Simulation Context" width="672" />
<p class="caption">
Figure 10.5: Power Curves for Different Sample Sizes in Simulation Context
</p>
</div>
<p>In the figure showing power curves, solid dots are used to highlight power when <span class="math inline">\(H_0\)</span> is true (<span class="math inline">\(\mu = 5\)</span>, in which case rejecting <span class="math inline">\(H_0\)</span> represents a Type I error) as well as for the specific alternative-hypothesis value considered above, <span class="math inline">\(\mu = 5.75\)</span>. Notice that the green curve, corresponding to a sample size of <span class="math inline">\(n = 30\)</span> is located just above 0.80 when <span class="math inline">\(\mu = 5.75\)</span>, consistent with our calculation that <span class="math inline">\(n = 28\)</span> would be sufficient to achieve 80% power to detect this alternative value for <span class="math inline">\(\mu\)</span>.</p>
<div class="whitebox">
<div class="example">
<p><span id="exm:ht-pop-mean-t-example-power" class="example"><strong>Example 10.3  </strong></span>In the context of the soup-can data from Example <a href="chap-hypothesis-testing.html#exm:ht-pop-mean-t-example">10.1</a>, suppose we wish to estimate the power of our test to detect that the population mean equals <span class="math inline">\(835\)</span>; that is, supposing that <span class="math inline">\(H_A\)</span> is true and <span class="math inline">\(\mu = 835\)</span>, we wish to compute the probability that we would (correctly) reject <span class="math inline">\(H_0\)</span>.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="chap-hypothesis-testing.html#cb219-1" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n =</span> n, <span class="at">delta =</span> <span class="dv">835</span> <span class="sc">-</span> <span class="dv">830</span>, <span class="at">sd =</span> s, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb219-2"><a href="chap-hypothesis-testing.html#cb219-2" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;one.sample&quot;</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 15
##           delta = 5
##              sd = 10.96655
##       sig.level = 0.05
##           power = 0.3764037
##     alternative = two.sided</code></pre>
<p>Thus, we estimate that the one-sample <span class="math inline">\(t\)</span>-test has about 30% power to reject <span class="math inline">\(H_0: \mu = 830\)</span> if in fact <span class="math inline">\(\mu = 835\)</span>.</p>
<p>Suppose we wish to compute the sample size that would be required for this power to be 60%.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="chap-hypothesis-testing.html#cb221-1" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">power =</span> <span class="fl">0.60</span>, <span class="at">delta =</span> <span class="dv">835</span> <span class="sc">-</span> <span class="dv">830</span>, <span class="at">sd =</span> s, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb221-2"><a href="chap-hypothesis-testing.html#cb221-2" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;one.sample&quot;</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 25.53817
##           delta = 5
##              sd = 10.96655
##       sig.level = 0.05
##           power = 0.6
##     alternative = two.sided</code></pre>
<p>Rounding <em>up</em> to the nearest integer, we estimate that a sample size of <span class="math inline">\(n = 26\)</span> would be required for 60% power to detect that <span class="math inline">\(\mu = 835\)</span>.</p>
<p>Note that <code>n</code>, <code>power</code>, and <code>delta</code> arguments can be specified as vectors, enabling us to easily create e.g. a power curve (a plot of power for a variety of effect sizes).</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="chap-hypothesis-testing.html#cb223-1" tabindex="-1"></a>delta_vec <span class="ot">=</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="dv">15</span>, <span class="at">to =</span> <span class="dv">15</span>, <span class="at">length =</span> <span class="dv">500</span>)</span>
<span id="cb223-2"><a href="chap-hypothesis-testing.html#cb223-2" tabindex="-1"></a>power_vec <span class="ot">=</span> <span class="fu">power.t.test</span>(<span class="at">n =</span> n, <span class="at">delta =</span> delta_vec, <span class="at">sd =</span> s, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb223-3"><a href="chap-hypothesis-testing.html#cb223-3" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;one.sample&quot;</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)<span class="sc">$</span>power</span>
<span id="cb223-4"><a href="chap-hypothesis-testing.html#cb223-4" tabindex="-1"></a></span>
<span id="cb223-5"><a href="chap-hypothesis-testing.html#cb223-5" tabindex="-1"></a><span class="fu">plot</span>(mu0 <span class="sc">+</span> delta_vec, power_vec, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;True Mean&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Power&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-96"></span>
<img src="_main_files/figure-html/unnamed-chunk-96-1.png" alt="Estimated Power Curve for Soup-Can Example" width="576" />
<p class="caption">
Figure 10.6: Estimated Power Curve for Soup-Can Example
</p>
</div>
</div>
</div>
</div>
<div id="power-and-sample-size-calculations-for-mu" class="section level3 hasAnchor" number="10.6.1">
<h3><span class="header-section-number">10.6.1</span> Power and Sample Size Calculations for <span class="math inline">\(\mu\)</span><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations-for-mu" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the context of <span class="math inline">\(t\)</span>-based inference on a population mean, we used the <code>power.t.test</code> function for power and sample size calculations. In the context of <span class="math inline">\(z\)</span>-based inference on a population proportion, there is an analogous <code>power.prop.test</code> fuction.</p>
<div class="whitebox">
<div class="example">
<p><span id="exm:ht-pop-proportion-example-power" class="example"><strong>Example 10.4  </strong></span>In the context of the marketing data from Example <a href="chap-hypothesis-testing.html#exm:ht-pop-proportion-example">10.2</a>, suppose we wish to estimate the power of our test to detect that the population proportion equals 0.70; that is, supposing that <span class="math inline">\(H_A\)</span> is true and <span class="math inline">\(p = 0.70\)</span>, we wish to compute the probability that we would (correctly) reject <span class="math inline">\(H_0\)</span>.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="chap-hypothesis-testing.html#cb224-1" tabindex="-1"></a><span class="fu">power.prop.test</span>(<span class="at">n =</span> <span class="dv">150</span>, <span class="at">p1 =</span> <span class="fl">0.70</span>, <span class="at">p2 =</span> <span class="fl">0.75</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb224-2"><a href="chap-hypothesis-testing.html#cb224-2" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample comparison of proportions power calculation 
## 
##               n = 150
##              p1 = 0.7
##              p2 = 0.75
##       sig.level = 0.05
##           power = 0.1606579
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>We estimate that the one-sample <span class="math inline">\(z\)</span>-based test has about 16% power to reject <span class="math inline">\(H_0: p = 0.75\)</span> if in fact <span class="math inline">\(p = 0.70\)</span>.</p>
<p>As with <code>prop.t.test</code>, we can also use <code>power.prop.test</code> to compute the <em>sample size</em> required to achieve a specified power; to do so, we would leave the sample size argument blank and specify the desired power via the <code>power</code> argument.</p>
</div>
</div>
</div>
<div id="power-and-sample-size-calculations" class="section level3 hasAnchor" number="10.6.2">
<h3><span class="header-section-number">10.6.2</span> Power and Sample Size Calculations<a href="chap-hypothesis-testing.html#power-and-sample-size-calculations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To find the power of a test, the calculations can be complex. And so we instead point the reader to the <code>R</code> function <code>power.t.test</code>. This function is able to numerically compute either of power or required sample size. It has arguments for each of sample size, power, and "effect size" (in the context of a one-sample <span class="math inline">\(t\)</span>-test, "effect size" refers to the difference between the true population mean value and the value of the population mean under <span class="math inline">\(H_0\)</span> (i.e., <span class="math inline">\(\mu_0\)</span>)). If you specify two of these three values and leave the third argument blank, <code>R</code> will return the unspecified value.</p>
</div>
<div id="power-and-sample-size-calculations-for-chi2" class="section level3 hasAnchor" number="10.6.3">
<h3><span class="header-section-number">10.6.3</span> Power and Sample Size Calculations for <span class="math inline">\(\chi^2\)</span><a href="chap-hypothesis-testing.html#power-and-sample-size-calculations-for-chi2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just as with other hypothesis tests, we can compute the power of the above test about a population variance. As of this writing, R does not provide a built-in function like <code>power.t.test()</code> or <code>power.prop.test()</code> for power calculations about a population variance. However, a manual approach is relatively straightforward. For consistency with Example <a href="chap-hypothesis-testing.html#exm:ht-pop-proportion-example">10.2</a>, we present the following in the context of a one-sided alternative hypothesis; that is, we consider testing</p>
<p><span class="math display">\[
H_0: \sigma^2 = \sigma_0^2 \quad \text{vs.} \quad H_A: \sigma^2 &gt; \sigma_0^2
\]</span></p>
<p>As above, we use the test statistic</p>
<p><span class="math display">\[
\chi^2 = \frac{(n - 1)s^2}{\sigma_0^2}
\]</span></p>
<p>which follows a chi-squared distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom under <span class="math inline">\(H_0\)</span>. For a one-sided test with significance level <span class="math inline">\(\alpha\)</span>, the critical value is the <span class="math inline">\(1-\alpha\)</span> percentile of the <span class="math inline">\(\chi^2_{n - 1}\)</span> distribution.</p>
<p>To compute power for a particular alternative value <span class="math inline">\(\sigma^2 = \sigma_1^2 \ne \sigma_0^2\)</span>, we note that under this alternative, the test statistic follows a scaled chi-squared distribution:</p>
<p><span class="math display">\[
\chi^2 \sim \left( \frac{\sigma_1^2}{\sigma_0^2} \right) \cdot \chi^2_{n - 1}
\]</span></p>
<p>The power is the probability of rejecting <span class="math inline">\(H_0\)</span> when <span class="math inline">\(\sigma^2 = \sigma_1^2\)</span>, which can be calculated as:</p>
<p><span class="math display">\[
\text{Power} = P\left( \chi^2 &gt; \chi^2_{\alpha, n-1} \mid \sigma^2 = \sigma_1^2 \right)
\]</span></p>
<p>where <span class="math inline">\(\chi^2_{\alpha, n-1}\)</span> is the appropriate critical value.</p>
<p>We can compute this manually in <code>R</code>. In the context of Example <a href="chap-hypothesis-testing.html#exm:ht-pop-proportion-example">10.2</a>, suppose we wish to compute the power to reject <span class="math inline">\(H_0: \sigma^2 = 0.10\)</span> when the true value of <span class="math inline">\(\sigma^2\)</span> is 0.12:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="chap-hypothesis-testing.html#cb226-1" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.01</span></span>
<span id="cb226-2"><a href="chap-hypothesis-testing.html#cb226-2" tabindex="-1"></a>s2_0 <span class="ot">=</span> <span class="fl">0.10</span>       <span class="co"># Null value</span></span>
<span id="cb226-3"><a href="chap-hypothesis-testing.html#cb226-3" tabindex="-1"></a>s2_1 <span class="ot">=</span> <span class="fl">0.12</span>       <span class="co"># True value under H_A</span></span>
<span id="cb226-4"><a href="chap-hypothesis-testing.html#cb226-4" tabindex="-1"></a></span>
<span id="cb226-5"><a href="chap-hypothesis-testing.html#cb226-5" tabindex="-1"></a>scale <span class="ot">=</span> s2_0 <span class="sc">/</span> s2_1  <span class="co"># Scaling factor</span></span>
<span id="cb226-6"><a href="chap-hypothesis-testing.html#cb226-6" tabindex="-1"></a>crit_val <span class="ot">=</span> <span class="fu">qchisq</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, n <span class="sc">-</span> <span class="dv">1</span>)  <span class="co"># Critical value</span></span>
<span id="cb226-7"><a href="chap-hypothesis-testing.html#cb226-7" tabindex="-1"></a></span>
<span id="cb226-8"><a href="chap-hypothesis-testing.html#cb226-8" tabindex="-1"></a>power <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(crit_val <span class="sc">*</span> scale, n <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb226-9"><a href="chap-hypothesis-testing.html#cb226-9" tabindex="-1"></a>power</span></code></pre></div>
<pre><code>## [1] 0.04232558</code></pre>
<p>We estimate a power of <span class="math inline">\(\sim 3\)</span>% to reject <span class="math inline">\(H_0: \sigma^2 = 0.1\)</span> when <span class="math inline">\(\sigma^2 = 0.12\)</span>.</p>
<p>The same approach can be adapted to determine the sample size required to achieve a desired power by iterating over candidate values of <span class="math inline">\(n\)</span> until the computed power meets the specified threshold.</p>
</div>
</div>
<div id="exploring-hypothesis-test-via-simulation" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> Exploring Hypothesis Test via simulation<a href="chap-hypothesis-testing.html#exploring-hypothesis-test-via-simulation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="the-test-statistic-and-its-sampling-distribution-assuming-h_0-is-true" class="section level3 hasAnchor" number="10.7.1">
<h3><span class="header-section-number">10.7.1</span> The Test Statistic and its Sampling Distribution: Assuming <span class="math inline">\(H_0\)</span> is true<a href="chap-hypothesis-testing.html#the-test-statistic-and-its-sampling-distribution-assuming-h_0-is-true" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In a hypothesis test, we wish to quantify how consistent the observed data are with the assumption that the null hypothesis (<span class="math inline">\(H_0\)</span>) is true. If the data appear consistent with <span class="math inline">\(H_0\)</span>, we maintain our assumption. But if the data appear <em>inconsistent</em> with <span class="math inline">\(H_0\)</span> (that is, if they would be very unlikely to occur if <span class="math inline">\(H_0\)</span> were true) then we have grounds to question that assumption and consider the possibility that the alternative hypothesis (<span class="math inline">\(H_A\)</span>) is true instead.</p>
<p>To evaluate this consistency, we define a <strong>test statistic</strong>, which is a numerical summary of the data specifically designed to measure agreement between the observed data and the null hypothesis. Ideally, a test statistic is constructed in such a way that:</p>
<ul>
<li>If <span class="math inline">\(H_0\)</span> is true, the test statistic is likely to fall in a "non-extreme" region (e.g., near 0 or near 1, depending on the context).</li>
<li>If <span class="math inline">\(H_A\)</span> is true, the test statistic is more likely to fall in an "extreme" region, far from its typical value under <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>To use the test statistic to make decisions, we must understand its <strong>sampling distribution under the assumption that <span class="math inline">\(H_0\)</span> is true</strong>. That is, we must answer the question:</p>
<blockquote>
<p><em>What values of the test statistic would we expect to see if <span class="math inline">\(H_0\)</span> were actually true?</em></p>
</blockquote>
<p>The shape and spread of this null sampling distribution allow us to determine how extreme our observed test statistic is. If the observed test statistic falls far into the tails of the null distribution, we will consider it unlikely to have occurred under <span class="math inline">\(H_0\)</span>, and may choose to reject <span class="math inline">\(H_0\)</span>.</p>
<p>In many standard testing scenarios, the null distribution of the test statistic follows a well-known theoretical distribution (such as a standard Normal, <span class="math inline">\(t\)</span>, or <span class="math inline">\(\chi^2\)</span> distribution), either exactly or approximately. In other cases, especially when assumptions are questionable or sample sizes are small, we may instead estimate the null distribution empirically using simulation or resampling techniques (e.g., the bootstrap).</p>
</div>
<div id="simulation-study-repeated-hypothesis-testing-under-h_0-and-h_a" class="section level3 hasAnchor" number="10.7.2">
<h3><span class="header-section-number">10.7.2</span> Simulation Study: Repeated Hypothesis Testing Under <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span><a href="chap-hypothesis-testing.html#simulation-study-repeated-hypothesis-testing-under-h_0-and-h_a" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To build intuition for the logic of hypothesis testing, we can conduct a simulation study (like we did for confidence intervals). We will consider the setting of testing a hypothesis about a single population mean. Suppose the population standard deviation is known to be <span class="math inline">\(\sigma = 1.4\)</span>, and we take samples of size <span class="math inline">\(n = 15\)</span>.</p>
<p>We wish to test the following hypotheses:</p>
<p><span class="math display">\[
H_0: \mu = 5 \quad \text{vs.} \quad H_A: \mu \neq 5
\]</span></p>
<p>We will use the sample mean <span class="math inline">\(\bar{x}\)</span> as our test statistic and assume the population distribution is Normal; note, later in this chapter, we will replace <span class="math inline">\(\bar{x}\)</span> as the test statistic with a better option, but we use temporarily use <span class="math inline">\(\bar{x}\)</span> to keep things simple for illustration purposes. Under <span class="math inline">\(H_0\)</span>, the test statistic follows a Normal distribution:
<span class="math display">\[
\bar{X} \overset{H_0}{\sim} N \left( 5, \frac{1.4}{\sqrt{15}} \right)
\]</span>
That is, recalling Section <a href="chap-sampling-distributions.html#sec-distn-sample-mean">8.3</a>:</p>
<ul>
<li>Because the population distribution is Normal, we know that the sampling distribution of <span class="math inline">\(\bar{X}\)</span> is also Normal.</li>
<li>Also, we know that the mean of the sampling distribution of <span class="math inline">\(\bar{X}\)</span> is equal to the population mean, whatever it is, and the standard deviation (a.k.a. standard error) of <span class="math inline">\(\bar{X}\)</span> is equal to the population standard deviation divided by the square root of the sample size. Because our strategy for hypothesis testing is to consider the likelihood of a value of our test statistic as or more extreme as our observed value, we set as the mean of the sampling distribution of <span class="math inline">\(\bar{X}\)</span> the null-hypothesized value of <span class="math inline">\(\mu\)</span>, here equal to 5.</li>
</ul>
<p>To explore the behavior of hypothesis testing under both <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>, we conduct the following simulation:</p>
<ul>
<li>We simulate 10,000 samples of size <span class="math inline">\(n = 15\)</span> from a Normal distribution with <span class="math inline">\(\mu = 5.0\)</span> (i.e., assuming <span class="math inline">\(H_0\)</span> is true).</li>
<li>For each sample, we compute the test statistic (<span class="math inline">\(\bar{x}\)</span>) and the corresponding two-sided <span class="math inline">\(p\)</span>-value.</li>
<li>We repeat the same process assuming <span class="math inline">\(\mu = 5.25\)</span> (i.e., under one example alternative).</li>
</ul>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="chap-hypothesis-testing.html#cb228-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb228-2"><a href="chap-hypothesis-testing.html#cb228-2" tabindex="-1"></a></span>
<span id="cb228-3"><a href="chap-hypothesis-testing.html#cb228-3" tabindex="-1"></a>n        <span class="ot">=</span> <span class="dv">15</span></span>
<span id="cb228-4"><a href="chap-hypothesis-testing.html#cb228-4" tabindex="-1"></a>sigma    <span class="ot">=</span> <span class="fl">1.4</span></span>
<span id="cb228-5"><a href="chap-hypothesis-testing.html#cb228-5" tabindex="-1"></a>mu_null  <span class="ot">=</span> <span class="fl">5.0</span></span>
<span id="cb228-6"><a href="chap-hypothesis-testing.html#cb228-6" tabindex="-1"></a>mu_alt   <span class="ot">=</span> <span class="fl">5.25</span></span>
<span id="cb228-7"><a href="chap-hypothesis-testing.html#cb228-7" tabindex="-1"></a>alpha    <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb228-8"><a href="chap-hypothesis-testing.html#cb228-8" tabindex="-1"></a>num_sims <span class="ot">=</span> <span class="dv">10000</span></span>
<span id="cb228-9"><a href="chap-hypothesis-testing.html#cb228-9" tabindex="-1"></a></span>
<span id="cb228-10"><a href="chap-hypothesis-testing.html#cb228-10" tabindex="-1"></a><span class="co"># P-value distributions under H_0 and (one specific case of) H_A</span></span>
<span id="cb228-11"><a href="chap-hypothesis-testing.html#cb228-11" tabindex="-1"></a>pvals_null <span class="ot">=</span> <span class="fu">get_pvals</span>(mu_null)</span>
<span id="cb228-12"><a href="chap-hypothesis-testing.html#cb228-12" tabindex="-1"></a>pvals_alt <span class="ot">=</span> <span class="fu">get_pvals</span>(mu_alt)</span>
<span id="cb228-13"><a href="chap-hypothesis-testing.html#cb228-13" tabindex="-1"></a></span>
<span id="cb228-14"><a href="chap-hypothesis-testing.html#cb228-14" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb228-15"><a href="chap-hypothesis-testing.html#cb228-15" tabindex="-1"></a><span class="fu">hist</span>(pvals_null, <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>, </span>
<span id="cb228-16"><a href="chap-hypothesis-testing.html#cb228-16" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;P-values under &quot;</span>, H[<span class="dv">0</span>], <span class="st">&quot;: &quot;</span>, mu, <span class="st">&quot; = 5.0&quot;</span>)),</span>
<span id="cb228-17"><a href="chap-hypothesis-testing.html#cb228-17" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;p-value&quot;</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb228-18"><a href="chap-hypothesis-testing.html#cb228-18" tabindex="-1"></a><span class="fu">hist</span>(pvals_alt, <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>, </span>
<span id="cb228-19"><a href="chap-hypothesis-testing.html#cb228-19" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;P-values when &quot;</span>, mu, <span class="st">&quot; = 5.25&quot;</span>)),</span>
<span id="cb228-20"><a href="chap-hypothesis-testing.html#cb228-20" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;p-value&quot;</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:simulate-hypothesis-test"></span>
<img src="_main_files/figure-html/simulate-hypothesis-test-1.png" alt="Simulation-Based Distribution of P-Values Under the Null Hypothesis and For One Example Alternative Mean Value" width="960" />
<p class="caption">
Figure 10.7: Simulation-Based Distribution of P-Values Under the Null Hypothesis and For One Example Alternative Mean Value
</p>
</div>
<p>The distribution of p-values when <span class="math inline">\(H_0\)</span> is true can be mathematically shown to follow the <strong>Uniform</strong> distribution between 0 and 1; the Uniform distribution, as its name suggests, distributes its probability <em>uniformly</em> across the allowable range of values (here, the interval [0, 1]). We also considered one possible alternative-hypothesis case, corresponding to <span class="math inline">\(\mu = 5.25\)</span>, and we see that the distribution of p-values in this case has more probability assigned to small p-values.</p>
<p>Our strategy for making our decision regarding <span class="math inline">\(H_0\)</span> in a hypothesis test is to <em>reject <span class="math inline">\(H_0\)</span></em> if the p-value is sufficiently small or <em>fail to reject <span class="math inline">\(H_0\)</span></em> if the p-value is not sufficiently small. Even if <span class="math inline">\(H_0\)</span> is true, there is non-zero probability that we will observe a "small" p-value (and, hence, incorrectly reject <span class="math inline">\(H_0\)</span>). However, as suggested by the above distribution of p-values for the alternative-hypothesis case <span class="math inline">\(\mu = 5.25\)</span>, we are <em>more likely</em> to observe a small p-value (and, hence, more likely to reject <span class="math inline">\(H_0\)</span>) if <span class="math inline">\(H_0\)</span> is not true. How "small" is "small" when evaluating a p-value? We address this in the following section.</p>
</div>
<div id="bootstrap-hypothesis-tests" class="section level3 hasAnchor" number="10.7.3">
<h3><span class="header-section-number">10.7.3</span> Bootstrap Hypothesis Tests<a href="chap-hypothesis-testing.html#bootstrap-hypothesis-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The bootstrap can also be used to carry out a hypothesis test for a population parameter when standard parametric tests may not be valid or desirable. In particular, we can adapt the basic bootstrap percentile method from Chapter <a href="chap-confidence-intervals.html#chap-confidence-intervals">9</a> to construct a nonparametric test of the null hypothesis <span class="math inline">\(H_0: \theta = \theta_0\)</span>, where <span class="math inline">\(\theta\)</span> is a population parameter such as a mean.</p>
<p>The basic idea is to simulate what the distribution of the test statistic would look like under the null hypothesis. This is done by <em>centering the sample data</em> so that <span class="math inline">\(H_0\)</span> is true, then resampling from the centered data to approximate the null distribution of the test statistic. We can then compare our observed test statistic to this distribution to obtain a p-value.</p>
</div>
<div id="the-basic-bootstrap-hypothesis-test-procedure" class="section level3 hasAnchor" number="10.7.4">
<h3><span class="header-section-number">10.7.4</span> The Basic Bootstrap Hypothesis Test Procedure<a href="chap-hypothesis-testing.html#the-basic-bootstrap-hypothesis-test-procedure" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="procedure">
<p><strong>Steps for a Two-Sided Bootstrap Hypothesis Test</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Compute the observed test statistic</strong> (e.g., the sample mean) from the original data.</li>
<li><strong>Center the data</strong> by subtracting the observed statistic and adding the null value <span class="math inline">\(\theta_0\)</span>. This transforms the data to make <span class="math inline">\(H_0\)</span> true.</li>
<li><strong>Resample with replacement</strong> from the centered data to create many bootstrap samples (e.g., 10,000 resamples).</li>
<li><strong>Compute the test statistic</strong> for each bootstrap sample.</li>
<li><strong>Calculate the p-value</strong> as the proportion of bootstrap statistics that are as or more extreme than the observed test statistic (in both directions).</li>
</ol>
</div>
<div class="whitebox">
<div class="example">
<p><span id="exm:bootstrap-ht-leaf" class="example"><strong>Example 10.5  </strong></span>Recall Example <a href="chap-confidence-intervals.html#exm:bootstrap-skewed">9.10</a>, in which a botanist measured the lengths (in cm) of 15 leaves from a particular species and obtained the following sample:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="chap-hypothesis-testing.html#cb229-1" tabindex="-1"></a>leaf <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">2.1</span>, <span class="fl">2.5</span>, <span class="fl">2.7</span>, <span class="fl">2.8</span>, <span class="fl">3.0</span>, <span class="fl">3.1</span>, <span class="fl">3.2</span>, <span class="fl">3.5</span>, <span class="fl">3.6</span>, <span class="fl">4.0</span>, <span class="fl">4.5</span>, <span class="fl">5.2</span>, <span class="fl">5.8</span>, <span class="fl">6.4</span>, <span class="fl">8.0</span>)</span></code></pre></div>
<p>Suppose we wish to test the null hypothesis that the population mean leaf length is 4 cm, against the two-sided alternative that it is not:</p>
<p><span class="math display">\[
H_0: \mu = 4 \quad \text{vs.} \quad H_A: \mu \ne 4
\]</span></p>
<p>The observed sample mean is:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="chap-hypothesis-testing.html#cb230-1" tabindex="-1"></a>x_bar <span class="ot">=</span> <span class="fu">mean</span>(leaf)</span>
<span id="cb230-2"><a href="chap-hypothesis-testing.html#cb230-2" tabindex="-1"></a>x_bar</span></code></pre></div>
<pre><code>## [1] 4.026667</code></pre>
<p>To simulate the distribution of the sample mean under <span class="math inline">\(H_0\)</span>, we center the data so that the sample mean equals the null value of 4:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="chap-hypothesis-testing.html#cb232-1" tabindex="-1"></a>leaf_centered <span class="ot">=</span> leaf <span class="sc">-</span> x_bar <span class="sc">+</span> <span class="dv">4</span></span></code></pre></div>
<p>We then generate 10,000 bootstrap resamples from the centered data, computing the sample mean for each:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="chap-hypothesis-testing.html#cb233-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb233-2"><a href="chap-hypothesis-testing.html#cb233-2" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">10000</span></span>
<span id="cb233-3"><a href="chap-hypothesis-testing.html#cb233-3" tabindex="-1"></a>boot_means <span class="ot">=</span> <span class="fu">replicate</span>(B, <span class="fu">mean</span>(<span class="fu">sample</span>(leaf_centered, <span class="fu">length</span>(leaf), </span>
<span id="cb233-4"><a href="chap-hypothesis-testing.html#cb233-4" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span></code></pre></div>
<p>Finally, we compute the two-sided p-value as the proportion of bootstrap means that are at least as far from the null value as the observed sample mean:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="chap-hypothesis-testing.html#cb234-1" tabindex="-1"></a>obs_diff <span class="ot">=</span> <span class="fu">abs</span>(x_bar <span class="sc">-</span> <span class="dv">4</span>)</span>
<span id="cb234-2"><a href="chap-hypothesis-testing.html#cb234-2" tabindex="-1"></a>p_val <span class="ot">=</span> <span class="fu">mean</span>(<span class="fu">abs</span>(boot_means <span class="sc">-</span> <span class="dv">4</span>) <span class="sc">&gt;=</span> obs_diff)</span>
<span id="cb234-3"><a href="chap-hypothesis-testing.html#cb234-3" tabindex="-1"></a><span class="fu">round</span>(p_val, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.9557</code></pre>
<p>If this p-value is less than our chosen significance level <span class="math inline">\(\alpha = 0.05\)</span>, then we reject <span class="math inline">\(H_0\)</span>. Otherwise, we do not reject <span class="math inline">\(H_0\)</span>. In this example, we obtain a p-value of approximately 0.9557, so we fail to reject <span class="math inline">\(H_0\)</span> at the 5% level.</p>
</div>
</div>
<p>This simple approach allows us to conduct hypothesis tests without relying on strong parametric assumptions, making the bootstrap a powerful and flexible tool for inference. While the above example illustrates the basic idea clearly, real-world applications of bootstrap hypothesis tests can be more complex, especially when the test statistic is not a simple sample mean or when the null hypothesis is more difficult to impose.</p>

</div>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="chap-confidence-intervals.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-compare-two.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  },
  "info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
